### ISSUE TITLE
Android 10的ACCESS_BACKGROUND_LOCATION权限未兼容

### ISSUE THREAD

**Issue by zwping** [guolindev/PermissionX#1]
> mi mix3 android 10版本
> targetSdkVersion=29

```
PermissionX.init(this)
.permissions(ACCESS_FINE_LOCATION, ACCESS_COARSE_LOCATION, ACCESS_BACKGROUND_LOCATION)
.request { allGranted, grantedList, deniedList ->
    println("grantedList:$grantedList")
    println("deniedList:$deniedList")
    ......
}
```
当点击“仅在使用时访问”，权限被判断为拒绝，日志如下
```
grantedList:[android.permission.ACCESS_FINE_LOCATION, android.permission.ACCESS_COARSE_LOCATION]
deniedList:[android.permission.ACCESS_BACKGROUND_LOCATION]
```

**Comment by guolindev** [comment]
当点击“仅在使用时访问”，那不就是你拒绝了ACCESS_BACKGROUND_LOCATION权限吗。

如果想要允许ACCESS_BACKGROUND_LOCATION权限，你得点击始终允许。

**Comment by guolindev** [comment]
不过我手上并没有小米手机，我是在自己的Pixel手机上测试的Android 10兼容，我认为是没有问题的。

如果在小米手机上是另外一种现象，请再回复我。

**Comment by zwping** [comment]
对ACCESS_BACKGROUND_LOCATION权限理解有出入🙏

[官方文档](https://developer.android.com/reference/android/Manifest.permission#ACCESS_BACKGROUND_LOCATION)
