### ISSUE TITLE
Bugly 捕捉到的异常 kotlin.UninitializedPropertyAccessException  lateinit property permissionBuilder has not been initialized

### ISSUE THREAD

**Issue by 1312128240** [guolindev/PermissionX#100]
### **java.lang.RuntimeException:Failure delivering result ResultInfo{who=@android:requestPermissions:, request=65537, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.puxiansheng.www/com.puxiansheng.www.ui.map.MapActivity}: kotlin.UninitializedPropertyAccessException: lateinit property permissionBuilder has not been initialized**
2
android.app.ActivityThread.deliverResults(ActivityThread.java:4335)
3
......
4
Caused by:
5
kotlin.UninitializedPropertyAccessException:lateinit property permissionBuilder has not been initialized
6
com.permissionx.guolindev.InvisibleFragment.onRequestPermissionsResult(InvisibleFragment.kt:108)
7
androidx.fragment.app.FragmentActivity.onRequestPermissionsResult(FragmentActivity.java:768)
8
android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7508)
9
android.app.Activity.dispatchActivityResult(Activity.java:7359)
10
android.app.ActivityThread.deliverResults(ActivityThread.java:4331)
11
android.app.ActivityThread.handleSendResult(ActivityThread.java:4379)
12
android.app.ActivityThread.-wrap19(Unknown Source:0)
13
android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)
14
android.os.Handler.dispatchMessage(Handler.java:106)
15
android.os.Looper.loop(Looper.java:176)
16
android.app.ActivityThread.main(ActivityThread.java:6651)
17
java.lang.reflect.Method.invoke(Native Method)
18
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
19
com.android.internal.os.ZygoteInit.main(ZygoteInit.java:824)

**Comment by 1312128240** [comment]
系统版本

Android 8.1.0,level 27

ROM

XiaoMi/MIUI

CPU架构

arm64-v8a
设备机型

Redmi 5 Plus

**Comment by guolindev** [comment]
你用的是什么版本的PermissionX，我怎么感觉好像很老的样子，因为从你的堆栈上看，InvisibleFragment还是kt的，但是PermissionX从1.2开始InvisibleFragment就改成用Java写了，这个空指针的情况也在很早之前就修复了，可以参考这个issue https://github.com/guolindev/PermissionX/issues/10

**Comment by 1312128240** [comment]
好，哪我升级下
