### ISSUE TITLE
META-INF文件夹下的library_release.kotlin_module文件命名重复

### ISSUE THREAD

**Issue by cs9420** [guolindev/PermissionX#102]
郭婶 这个文件命名会跟我其他的库命名重复了 我给排除了 但使用会有影响吗？

**Comment by guolindev** [comment]
这是错是我当初库的命名没有起好，你可以更新下最新的1.5.0版本，应该不会再出现这个错误了，当然手动排除应该也没事，因为我这边没有提供顶层函数的对外接口，所以不会受影响。
