### ISSUE TITLE
InvisibleFragment not attached to Activity

### ISSUE THREAD

**Issue by wiseideal** [guolindev/PermissionX#103]
java.lang.IllegalStateException: Fragment InvisibleFragment{2091c95 (0613e794-c08a-4702-bfae-a05ab8ffc074) InvisibleFragment} not attached to Activity
        at androidx.fragment.app.Fragment.requestPermissions(Fragment.java:1315)
        at com.permissionx.guolindev.request.InvisibleFragment.requestNow(InvisibleFragment.java:79)
        at com.permissionx.guolindev.request.PermissionBuilder.requestNow(PermissionBuilder.java:371)
        at com.permissionx.guolindev.request.RequestNormalPermissions.request(RequestNormalPermissions.java:62)
        at com.permissionx.guolindev.request.RequestChain.runTask(RequestChain.java:55)
        at com.permissionx.guolindev.request.PermissionBuilder.request(PermissionBuilder.java:248)

测试机型为vivo 8.1版本

>PermissionX.init(this).permissions(
                Manifest.permission.READ_EXTERNAL_STORAGE,
                Manifest.permission.WRITE_EXTERNAL_STORAGE,
                Manifest.permission.ACCESS_NETWORK_STATE,
                Manifest.permission.ACCESS_WIFI_STATE,
                Manifest.permission.BLUETOOTH,
                Manifest.permission.READ_PHONE_STATE,
                Manifest.permission.CHANGE_WIFI_STATE,
                Manifest.permission.MODIFY_AUDIO_SETTINGS)
                .onForwardToSettings(new ForwardToSettingsCallback() {
                    @Override
                    public void onForwardToSettings(ForwardScope scope, List<String> deniedList) {
                        scope.showForwardToSettingsDialog(deniedList, "BLA BLA", "立即打开", "残忍拒绝");
                    }
                })
                .explainReasonBeforeRequest()
                .request(new RequestCallback() {
                    @Override
                    public void onResult(boolean allGranted, List<String> grantedList, List<String> deniedList) {
                        if(deniedList.contains(Manifest.permission.READ_EXTERNAL_STORAGE) || deniedList.contains(Manifest.permission.WRITE_EXTERNAL_STORAGE)){
                            if (AppInfoUtil.isStorageRequest(SplashActivity.this)){
                                finish();
                                return;
                            }
                        }
                        onAppStart();
                    }
                });

此bug出现几率大概为50% 并不是必现 在其他型号高版本中没有发现此类问题

**Comment by guolindev** [comment]
这个错误感觉有可能是你请求权限过早导致的，建议可以稍微向后延一延，等Activity或Fragment的生命周期都执行完了，再去请求权限，或许就不会出现这个问题了。
