### ISSUE TITLE
使用 explainReasonBeforeRequest() 有可能弹两次弹窗

### ISSUE THREAD

**Issue by navyifanr** [guolindev/PermissionX#104]
当使用了explainReasonBeforeRequest()，在弹出系统授权前，弹自定义的授权弹窗，如果所有权限都点击了「下次不再提醒」，那下次再申请时，会弹两次弹窗，一个是授权前的弹窗，一个是引导去设置页面授权的弹窗，这是bug，还是设计如此？感觉体验不太好

**Comment by guolindev** [comment]
我会再去检查一下代码，但是大概率应该是设计如此了。之前我印象中是有这样逻辑上的bug，但是我后来分析下来应该是没办法改，再加上是小众场景就忽略了。我这次再double check一下，如果能改尽量改掉，如果不能那就还是只能这样了。

**Comment by guolindev** [comment]
这个我又再次检查一遍，确实是设计如此，并没有一个简单的方案可以解决。

原因是判断是否要引导去设置页面授权的弹窗，需要在权限请求之后才能判断，而explainReasonBeforeRequest()的弹窗是在权限请求之前就会调用了，所以它并不能知道后面会不会再弹一次框，也就出现了弹两次的情况。

我建议的一种解决方案是，可以建议让两种弹窗上的样式或文字提示区别大一点，这样能让用户意识到这是两个不同的弹窗，而不是同一个弹窗弹了两次。

**Comment by navyifanr** [comment]
> 这个我又再次检查一遍，确实是设计如此，并没有一个简单的方案可以解决。
> 
> 原因是判断是否要引导去设置页面授权的弹窗，需要在权限请求之后才能判断，而explainReasonBeforeRequest()的弹窗是在权限请求之前就会调用了，所以它并不能知道后面会不会再弹一次框，也就出现了弹两次的情况。
> 
> 我建议的一种解决方案是，可以建议让两种弹窗上的样式或文字提示区别大一点，这样能让用户意识到这是两个不同的弹窗，而不是同一个弹窗弹了两次。

既然弹两次弹窗，从逻辑上无法避免，那能不能做到，判断到弹第二个弹窗的时候，取消掉第一个弹窗呢？

**Comment by guolindev** [comment]
你弹第二个框的时候第一个框早就没了，第一个框不取消，也走不到后面的逻辑去弹第二个框。

**Comment by zhbzhbzhbz** [comment]
@guolindev 我也遇到了这个问题，那请问是否有可能先判断“未申请过权限”还是“已经拒绝过”？如果是后者，开发者就可以手动不调用`onExplainRequestReason`了

**Comment by whatisjava** [comment]
> @guolindev 我也遇到了这个问题，那请问是否有什么API能判断“未申请过权限”还是“已经拒绝过”？如果是后者，开发者就可以手动不调用`onExplainRequestReason`了； 或者还有一个笨办法的话，开发者可以**在request里回调里，用sp去记录用户是否拒绝了**，这样下次就可以根据这个来判断是否要弹第一个窗？ 我是这么写的，亲测有效：
> 
> ```
> private static final String KEY = "ContinuousPositioningDenied";
> 
> private static boolean isDenied(Context context) {
>     SharedPreferences sp = context.getSharedPreferences(SP_NAME, Context.MODE_PRIVATE);
>     return sp.getBoolean(KEY, false);
> }
> 
> private static void setDenied(Context context) {
>     SharedPreferences.Editor editor = context.getSharedPreferences(SP_NAME, Context.MODE_PRIVATE).edit();
>     editor.putBoolean(KEY, true);
>     editor.apply();
> }
> 
> public static void requestContinuousLocation(FragmentActivity activity){
>     PermissionBuilder permissionBuilder = PermissionX
>         .init(activity)
>         // 这里必须三个权限都写，否则如果用户手动设置了“拒绝”，就弹不出对话框
>         .permissions(Manifest.permission.ACCESS_FINE_LOCATION, Manifest.permission.ACCESS_COARSE_LOCATION, Manifest.permission.ACCESS_BACKGROUND_LOCATION);
>     if (!isDenied(activity)) {
>         permissionBuilder = permissionBuilder.onExplainRequestReason(new ExplainReasonCallback() {
>             @Override
>             public void onExplainReason(@NonNull ExplainScope scope, @NonNull List<String> deniedList) {
>                 scope.showRequestReasonDialog(deniedList, "为确保后台定位，接下来请点击【始终允许】", "去设置");
>             }
>         });
>     }
>     // 用户如果点了拒绝，会在此处回调
>     permissionBuilder.onForwardToSettings((scope, deniedList) -> {
>         scope.showForwardToSettingsDialog(deniedList, "为确保后台定位，需点击【权限管理】→【定位】→【始终允许】", "去设置");
>     }).request((allGranted, grantedList, deniedList) -> {
>         if (!allGranted) {
>             setDenied(activity); 
>         }
>     });
> }
> ```

确实是，好像没有什么方法可以用来判断某个权限没授权是因为没申请过还是被拒绝授权的，只能自己记本地，不过这种方式也有问题，假如系统在app很长一段时间未使用后会把这个权限收回，再依赖本地记录就有问题了
