### ISSUE TITLE
权限拒绝之后的提示弹窗能不能再灵活一点

### ISSUE THREAD

**Issue by henryzhu-dev** [guolindev/PermissionX#105]
onExplainRequestReason方法中可以执行scope.showRequestReasonDialog()弹出提示框以让用户再次考虑授权，虽然1.4版本弹框比较漂亮，但是风格跟项目里的不一致，比如弹窗的圆角、控件摆放位置、字体大小等，最好能自定义弹窗，然后暴露继续执行的方法让开发者去处理

**Comment by guolindev** [comment]
自定义弹窗这个1.3就已经支持了，你可以参考这篇文章看一下使用方法 https://guolin.blog.csdn.net/article/details/107427463
