### ISSUE TITLE
init能否添加传入context的

### ISSUE THREAD

**Issue by Louiswang86** [guolindev/PermissionX#108]

**Comment by yinanwang1** [comment]
同求
想把Acp替换，因为Acp存在很多问题并且不更新了。 但是发现Acp是直接传入一个context的。

**Comment by guolindev** [comment]
不好意思，这是不可能的，Google的设计就是要求运行时权限的请求一定要附着于某个界面上，如果允许传入context，那么就意味着可以无界面请求权限，背离Google设计的初衷了。

至于其它库能实现传入context，那是用了一些违背良好代码设计的黑代码，我并不想要在PermissionX中引入类似的黑代码，所以这个需求我是无法完成的，谢谢理解。
