### ISSUE TITLE
请问，能添加安装apk权限的方法吗？

### ISSUE THREAD

**Issue by jingzz1** [guolindev/PermissionX#11]
AndPermission就有这个功能，但直接跳转到设置界面，感觉这做法对用户非常不友好

**Comment by guolindev** [comment]
安装apk权限是必须要跳转到设置界面的，这个权限因为不需要我们自己主动申请，只需要在AndroidManifest里面声明一下REQUEST_INSTALL_PACKAGES权限就行了。

当你跳转到安装apk界面的时候，如果权限还没有打开，系统会自动跳转到设置页面，并不需要我们手动操作任何东西。

AndPermission应该也是这么处理的，只要在高于8.0的系统版本上，没有办法手动替用户打开安装权限的。
