### ISSUE TITLE
想做下扩展

### ISSUE THREAD

**Issue by jialongsun** [guolindev/PermissionX#110]
我想使用默认的dialog,但是使用的是我自己的主题,因为在启动页面的时候,设置了特殊的背景,在调用默认的 defaultdialog的时候,弹窗会变形特别严重,是否可以提供下重载方法.

**Comment by guolindev** [comment]
那你就使用自定义对话框就好了，PermissionX本身就提供了这个接口，你可以把默认对话框的代码复制过去，再做下你自己的订制即可。
