### ISSUE TITLE
获取定位权限有问题

### ISSUE THREAD

**Issue by jingzz1** [guolindev/PermissionX#113]
手机：荣耀9x 
系统：android10
ui: EMUI10.1.0  

获取 Manifest.permission.ACCESS_COARSE_LOCATION ，Manifest.permission.ACCESS_FINE_LOCATION 两个定位权限，选择拒绝并且不再提示，之后进入设置，手机授权"仅在使用期间允许",这时应该算是获取到权限，但request没有回调

**Comment by lihuiqiang123** [comment]
手机：oneplus 8
系统：android 11
也遇到了上述问题，点击“仅在使用期间允许”和“仅本次使用允许”都收不到 request 的回调，拒绝的回调可以收到

**Comment by lihuiqiang123** [comment]
手机：realme Q3 5G
系统：android 11
同样的问题

**Comment by guolindev** [comment]
那如果再触发一遍权限请求呢？会是什么结果

**Comment by jingzz1** [comment]
再触发一遍权限是正常的

**Comment by guolindev** [comment]
那就说明其实是已经授权了，没有回调的原因有可能是因为Activity跳转后，前一个Activity的部分资源被回收了，这种情况比较少见，但确实会发生，目前也没有什么解决办法，就是手动再触发一遍就可以了。
