### ISSUE TITLE
希望把Library的 androidX:1.3.0 ，由 implementation 换成compileOnly

### ISSUE THREAD

**Issue by orhan-lau** [guolindev/PermissionX#114]
觉得可能每个项目的androidX版本不一样

**Comment by guolindev** [comment]
很抱歉，这个是不行的。一是因为有的项目可能并没有自己引入androidx库，这样的话不做下额外引入，只引用permissionx就会报错，这样又会被别人提bug。另外很快permissionx要基于androidx 1.3.0的api去实现一些功能了，如果版本对应不上，你引入了之后也会报错。
