### ISSUE TITLE
为什么当我请求权限清单中有危险权限、额外新适配的权限的时候，开始授权时会默认先弹出Android授权窗口，授权完成才提示permissionX的dialog进行下一步授权？

正常来说:应该是不管有多少权限，都应该先弹出permissionX的dialog询问用户再调用Android授权呀。是我理解的用户逻辑不对嘛？直接一上来就让用户给权限可能会在某些手机卡屏或者体验不好，授权完再提示一个permissionX的弹窗显得很尴尬。
看gif比较直观，挺简单的一个逻辑，我写字太多了



### ISSUE THREAD

**Issue by 9292922** [guolindev/PermissionX#117]
![mmexport1629464578279.png](https://user-images.githubusercontent.com/25112746/130237421-b383f144-b368-4671-8295-40364b001a58.png)

![Video_20210820_085801_991.gif](https://user-images.githubusercontent.com/25112746/130237470-81baa346-1fcc-4cc5-925b-c5686780737a.gif)

```
//检查授权状态
    private void checkPermissions() {
        List<String> list = new ArrayList<>();
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.R && !Environment.isExternalStorageManager()) {
            list.add(Manifest.permission.MANAGE_EXTERNAL_STORAGE);
        }

        if (!PermissionX.isGranted(MainActivity.this, Manifest.permission.WRITE_EXTERNAL_STORAGE)) {
            list.add(Manifest.permission.WRITE_EXTERNAL_STORAGE);
        }
        if (!PermissionX.isGranted(MainActivity.this, Manifest.permission.READ_EXTERNAL_STORAGE)) {
            list.add(Manifest.permission.READ_EXTERNAL_STORAGE);
        }
        if (!list.isEmpty()) {
            PermissionX.init(MainActivity.this)
                    .permissions(list).onExplainRequestReason((scope, deniedList) -> scope.showRequestReasonDialog(deniedList, "清理君需要你允许这些权限才能正常使用", "允许", "拒绝"))
                    .request((allGranted, grantedList, deniedList) -> {
                        if (allGranted) {
                            checkRootPermission();
                        } else {
                            Snackbar.make(fab, "请不要拒绝授权", Snackbar.LENGTH_SHORT).setAction("重新授权", v -> checkPermissions()).show();
                        }
                    });
        } else {
            checkRootPermission();
        }
    }
```

**Comment by guolindev** [comment]
主页文档中有讲这个功能 https://github.com/guolindev/PermissionX#explain-before-request

**Comment by 9292922** [comment]
> 主页文档中有讲这个功能 https://github.com/guolindev/PermissionX#explain-before-request

好的，谢谢您，打搅了

**Comment by 9292922** [comment]
@guolindev 
刚刚跑步回来试过了，利用explainReasonBeforeRequest()达到了效果，谢谢。另外还有一点，就是一起申请特殊权限、危险权限的时候，对话框不会跟多个危险权限一样列在同一个dialog，然后再一一申请。而是一项一项弹出dialog，郭神你也是注意细节的滴，你看看哪样好一点？是新版本的特殊权限还没有适配嘛？ 具体看gif，麻烦晒。

github:
![IMG_20210820_230642.jpg](https://user-images.githubusercontent.com/25112746/130253998-e9f63572-12e5-499b-a019-73013179c918.jpg)


实际效果:
![Video_20210820_110235_258.gif](https://user-images.githubusercontent.com/25112746/130253904-28e10dd7-9c0f-4efc-856b-766167f4f636.gif)

**Comment by 9292922** [comment]
> @guolindev 
> 刚刚跑步回来试过了，利用explainReasonBeforeRequest()达到了效果，谢谢。另外还有一点，就是一起申请特殊权限、危险权限的时候，对话框不会跟多个危险权限一样列在同一个dialog，然后再一一申请。而是一项一项弹出dialog，郭神你也是注意细节的滴，你看看哪样好一点？是新版本的特殊权限还没有适配嘛？ 具体看gif，麻烦晒。
> 
> github:
> ![IMG_20210820_230642.jpg](https://user-images.githubusercontent.com/25112746/130253998-e9f63572-12e5-499b-a019-73013179c918.jpg)
> 
> 
> 实际效果:
> ![Video_20210820_110235_258.gif](https://user-images.githubusercontent.com/25112746/130253904-28e10dd7-9c0f-4efc-856b-766167f4f636.gif)
> 

不过这也好像还可以，特殊权限分开授权，毕竟一般权限以一组的形式一起授权

**Comment by guolindev** [comment]
这个没有办法，特殊权限是每个都要单独跳到一个页面去授权的，只能一个一个独立显示，放到一起显示的话，跳转要跳到哪个页面用户就搞不清楚了。
