### ISSUE TITLE
Failure delivering result ResultInfo{who=@android:requestPermissions:, request=65537, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS

### ISSUE THREAD

**Issue by yz1309** [guolindev/PermissionX#119]
09-06 11:44:44.021 24517 24517 E AndroidRuntime: java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=65537, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {hc.ng.mt/com.app.apply.ApplyActivity}: java.lang.NullPointerException: Attempt to read from field 'java.util.Set l.n.a.c.d.h' on a null object reference

8909-06 11:44:44.021 24517 24517 E AndroidRuntime: at android.app.ActivityThread.deliverResults(ActivityThread.java:5042)
9009-06 11:44:44.021 24517 24517 E AndroidRuntime: at android.app.ActivityThread.handleSendResult(ActivityThread.java:5086)
9109-06 11:44:44.021 24517 24517 E AndroidRuntime: at android.app.ActivityThread.-wrap20(Unknown Source:0)
9209-06 11:44:44.021 24517 24517 E AndroidRuntime: at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2071)
9309-06 11:44:44.021 24517 24517 E AndroidRuntime: at android.os.Handler.dispatchMessage(Handler.java:109)
9409-06 11:44:44.021 24517 24517 E AndroidRuntime: at android.os.Looper.loop(Looper.java:166)
9509-06 11:44:44.021 24517 24517 E AndroidRuntime: at android.app.ActivityThread.main(ActivityThread.java:7555)
9609-06 11:44:44.021 24517 24517 E AndroidRuntime: at java.lang.reflect.Method.invoke(Native Method)
9709-06 11:44:44.021 24517 24517 E AndroidRuntime: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:469)
9809-06 11:44:44.021 24517 24517 E AndroidRuntime: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:963)
9909-06 11:44:44.021 24517 24517 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to read from field 'java.util.Set l.n.a.c.d.h' on a null object reference
10009-06 11:44:44.021 24517 24517 E AndroidRuntime: at com.permissionx.guolindev.request.InvisibleFragment.onRequestPermissionsResult(:1)
10109-06 11:44:44.021 24517 24517 E AndroidRuntime: at androidx.fragment.app.FragmentActivity.onRequestPermissionsResult(Unknown Source:68)
10209-06 11:44:44.021 24517 24517 E AndroidRuntime: at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7786)
10309-06 11:44:44.021 24517 24517 E AndroidRuntime: at android.app.Activity.dispatchActivityResult(Activity.java:7637)
10409-06 11:44:44.021 24517 24517 E AndroidRuntime: at android.app.ActivityThread.deliverResults(ActivityThread.java:5038)

**Comment by guolindev** [comment]
如果能提供不带混淆的日志更好，堆栈全混淆了确实无法定位问题，谢谢理解。
