### ISSUE TITLE
positiveText, negativeText设置按钮文案不显示

### ISSUE THREAD

**Issue by 13686996965** [guolindev/PermissionX#12]
依赖 permissionx:1.2.2
...
scope.showRequestReasonDialog(deniedList, “需要您同意以下权限才能正常使用”, "允许请求", "我还是拒绝")
...
权限被拒绝时，弹默认dialog，设置的确认、拒绝按钮文案没有正常显示

**Comment by guolindev** [comment]
PermissionX内部其实使用的就是系统的AlertDialog来弹出提示框，通过setPositiveButton和setNegativeButton来设置确认和取消按钮的。

根据你说的这个情况，感觉可能和特定手机有关，我目前没有遇到过这个问题。你可以尝试一下在同样这台手机上，直接使用系统的AlertDialog来弹出对话框，确定和取消按钮能不能正常显示。

**Comment by guolindev** [comment]
PermissionX 1.3.0版本加入了自定义权限提醒对话框的功能，或许可以解决掉这个问题，你可以尝试一下，参考文章 https://blog.csdn.net/guolin_blog/article/details/107427463。

因为一直没有反馈，我先把这个问题关掉了，如果后续还有疑问请再重新打开。
