### ISSUE TITLE
权限申请禁止后去设置返回后,创建showForwardToSettingsDialog会闪烁

### ISSUE THREAD

**Issue by sjw903** [guolindev/PermissionX#122]
PermissionX.init(this@AddSoundsActivity)
            .permissions(Manifest.permission.RECORD_AUDIO)
            .onExplainRequestReason { scope, deniedList ->
                scope.showRequestReasonDialog(
                    deniedList,
                    CONST_PERMISSION_RECORD_AUDIO,
                    CONST_PERMISSION_OK,
                    CONST_PERMISSION_CANCEL
                )
            }
            .onForwardToSettings { scope, deniedList ->
                scope.showForwardToSettingsDialog(
                    deniedList,
                    CONST_PERMISSION_TIP,
                    CONST_PERMISSION_SETTING,
                    CONST_PERMISSION_CANCEL
                )
            }
            .request { allGranted, _, _ ->
                if (allGranted) {
                    mIatDialog?.let {
                        it.setListener(mRecognizerDialogListener)
                        it.show()
                        val txt = it.window?.decorView?.findViewWithTag<TextView>("textlink")
                        if (txt != null) txt.text = ""
                    }
                }
            }
这个代码申请权限,如果选择拒绝,然后showForwardToSettingsDialog,然后通过Dialog选择去设置权限,去设置后什么也不操作,直接返回会闪烁

**Comment by sjw903** [comment]
你这个框架大体上挺好的,如果解决了上面的问题,还有如果showRequestReasonDialog,showForwardToSettingsDialog可以选择自定义弹出对话框就更好了

**Comment by sjw903** [comment]
是用的锤子手机测试的

**Comment by sjw903** [comment]
是用的Redmi10X, Android11,Miui12.5.4

**Comment by guolindev** [comment]
闪烁可能与机型相关，我这边测试的时候并没有发现闪烁现象。自定义弹出对话框可以参考这篇文章：
https://guolin.blog.csdn.net/article/details/107427463

**Comment by sjw903** [comment]
嗯,就是和机型有关系,不知道是处理问题,还是他们系统的问题

**Comment by guolindev** [comment]
你这边可以录制个视频让我看看闪烁是什么样子的吗？

**Comment by liu-wanshun** [comment]
我试了多个机型，都有这种情况，返回时转场动画与弹窗动画同时作用，看起来会有闪烁一下，所以建议不要使用onForwardToSettings。
因为onForwardToSettings返回时又requestAgain，然后发现没权限就又弹框了。
建议自己处理RequestCallback里自行处理永久拒绝的情况，或者修改源码不要requestAgain。

也可以看看：
https://gitee.com/liu_wanshun/PermissionX

**Comment by guolindev** [comment]
没有收到更多回复，暂时先将此问题关闭。
