### ISSUE TITLE
1.4升1.5报错：None of the following functions can be called with the arguments supplied

### ISSUE THREAD

**Issue by silveryTitan** [guolindev/PermissionX#124]
1.4版本升级1.5后 permissions方法报错 None of the following functions can be called with the arguments supplied: 
传参为vararg  permissions: String?=permissionArray
将?=permissionArray去掉就没事，方法不支持为空默认吗? 1.4版本这么使用是没有问题的

object PermissionXUtils {
    private val permissionArray = arrayOf(Manifest.permission.WRITE_EXTERNAL_STORAGE,
        Manifest.permission.READ_EXTERNAL_STORAGE,
        Manifest.permission.READ_PHONE_STATE,
        Manifest.permission.ACCESS_FINE_LOCATION,
        Manifest.permission.WRITE_CONTACTS,
        Manifest.permission.READ_CONTACTS,
        Manifest.permission.ACCESS_COARSE_LOCATION,
        Manifest.permission.READ_CONTACTS,
        Manifest.permission.WRITE_CONTACTS,
        Manifest.permission.WRITE_EXTERNAL_STORAGE,
//        Manifest.permission.INSTALL_SHORTCUT,
        Manifest.permission.CAMERA,
        Manifest.permission.RECORD_AUDIO)

    fun FragmentActivity.setPermission(vararg  permissions: String?=permissionArray, isSuccess: (Boolean)->Unit){
        PermissionX.init(this)
            .permissions(listOf(permissions)
            ).onExplainRequestReason { scope: ExplainScope, deniedList: List<String?>? ->
                scope.showRequestReasonDialog(deniedList,
                    "即将重新申请的权限是程序必须依赖的权限", "我已明白", "取消")
            }
            .onForwardToSettings { scope, deniedList ->
                scope.showForwardToSettingsDialog(deniedList, "您需要去应用程序设置当中手动开启权限", "我已明白", "取消")
            }
            .request { allGranted: Boolean, grantedList: List<String?>?, deniedList: List<String?> ->  //grantedList用于记录所有已被授权的权限，deniedList用于记录所有被拒绝的权限
                if (allGranted) { //是否所有申请的权限都已被授权
                    isSuccess.invoke(true)
                } else {
                    ToastUtil.showShort(this, "您拒绝了如下权限：$deniedList")
                }
            }
    }
}

**Comment by guolindev** [comment]
是的，其实你并没有任何理由去传空权限进来，所以只要你把你的参数列表上的问号去掉就可以了，这是一个bug修复，而不是bug新增。
