### ISSUE TITLE
申请特殊权限可以转应用页面吗

### ISSUE THREAD

**Issue by Luke1494652968** [guolindev/PermissionX#125]
现在使用的是1.5.1版本，申请特殊权限如悬浮窗时，跳转的是应用列表页面，需要找到当前应用，觉得用户会反馈体验不好。
看代码 在`showReasonOrGoSettings`为`false`时（应该是某权限被设置为拒绝且不再询问时，跳去应用的权限设置页面）走`forwardToSettings`方法， 这里 intent是设置了包名的，所以可以直接跳到应用页面
`        val intent = Intent(Settings.ACTION_APPLICATION_DETAILS_SETTINGS)
        val uri = Uri.fromParts("package", activity.packageName, null)
        intent.data = uri`
否则的话走`chainTask.requestAgain(permission)`
看开启悬浮窗的逻辑，不知道有没有找对，找到的是
`            Intent intent = new Intent(Settings.ACTION_MANAGE_OVERLAY_PERMISSION);
            startActivityForResult(intent, ACTION_MANAGE_OVERLAY_PERMISSION);`
这里没有设置包名

想问一下郭神 这里可以添加个包名在申请特殊权限时通过直接跳到应用页面吗？还是说已经支持了，只是我代码哪个地方调错了方法

**Comment by guolindev** [comment]
这个功能下个版本里会支持，预计不久后就会发布。

**Comment by Luke1494652968** [comment]
> 这个功能下个版本里会支持，预计不久后就会发布。

明白 谢谢郭神
