### ISSUE TITLE
forwardToSettings 跳转到应用权限设置页面

### ISSUE THREAD

**Issue by zhoujia456888** [guolindev/PermissionX#13]
forwardToSettings 跳转的是应用设置页面，权限请求的话还要在点一下，有些不懂的用户可能不太会操作（需要在一堆设置里面找到权限管理），是否可以直接跳转到应用权限设置页面？
[隔壁的方法](https://github.com/getActivity/XXPermissions/blob/master/library/src/main/java/com/hjq/permissions/PermissionSettingPage.java)

**Comment by guolindev** [comment]
隔壁的方法很秀，但是我不能去这样实现，因为这不是Android官方API的处理流程，而是针对国产机型做了太多侵入式的实现，会导致整个库变得不稳定（国产手机没有提供稳定的API，随时可能会变更）。

对于我来说，PermissionX并不是自己扩展了任何功能，完全是对系统原生API的封装，只是提供了更简洁的用法，所在非标准API的功能我是不考虑加进去的。
