### ISSUE TITLE
有个问题想请教下，如果用户拒绝并且选择不再询问，下次申请权限的时候怎么能让showRequestReasonDialog不出现呢

### ISSUE THREAD

**Issue by dingdangmao123** [guolindev/PermissionX#130]

**Comment by dingdangmao123** [comment]
貌似没法提前判断会不会弹出授权弹窗

**Comment by liu-wanshun** [comment]
你这个请求权限流程是有问题的。
1.默认先不解释请求原因，在请求结果回调里才解释。（合理应该是先解释再请求）
2.如果调用explainReasonBeforeRequest()设置先请求，这样每次都会解释权限，无论用户是否永久拒绝（合理应该是调用shouldShowRequestPermissionRationale()判断是否需要解释，需要解释的时候再弹框解释）

他说的意思应该是指第2点。

可以看看：
https://developer.android.google.cn/training/permissions/requesting

https://gitee.com/liu_wanshun/PermissionX

> 那你不要调用onForwardToSettings方法不就可以了

**Comment by guolindev** [comment]
没有收到更多回复，暂时先讲此问题关闭。
