### ISSUE TITLE
横屏下申请权限，弹窗里，权限描述显示不全

### ISSUE THREAD

**Issue by Michael-Liu-2008** [guolindev/PermissionX#132]

**Comment by guolindev** [comment]
Sorry，回复晚了。
为什么我觉得这个权限不是PermissionX的界面，而是小米手机弹出的界面。
你确定这是个和PermissionX有关的bug吗？要不要用原生API去请求权限看一下是不是也有同样的问题？

**Comment by Michael-Liu-2008** [comment]
试了下，用ActivityCompat.requestPermissions去请求也是同样的问题。 之前以为弹出的界面是PermissionX的。
