### ISSUE TITLE
多个权限能否同时允许,或者拒绝,像王者荣耀一样,登录时,有个权限列表,点击一下,全部权限通过,一个个点击太繁琐了

### ISSUE THREAD

**Issue by zkoalas** [guolindev/PermissionX#133]
多个权限能否同时允许,或者拒绝,像王者荣耀一样,登录时,有个权限列表,点击运行,全部权限通过,一个个点击太繁琐了

**Comment by hxmeie** [comment]
这玩意好像和系统有关系，华为的手机在商店里面下载的App，申请权限会弹个权限列表啥的，我们的App亲自测试过，确实是列表，但是自己安装的就是一个一个弹，代码都一样，但是应用行为不一样，很无语。。。魔改系统弄得，也没查到有代码可以这样

**Comment by guolindev** [comment]
这个确实和系统魔改有关，官方API是没有支持过这种功能的。PermissionX也只是在官方的API基础上做封装，所以恐怕无法支持你说的这种需求。
