### ISSUE TITLE
和RxPermission的对比

### ISSUE THREAD

**Issue by zengyunpeng** [guolindev/PermissionX#134]
郭神这个库和RxPermission调用方式区别不大,这个库对比rxPermission有哪些优势呢

**Comment by guolindev** [comment]
这个库不依赖于RxJava，所以我觉得和RxPermission并没有什么共同之处，用法上我也没觉得并不相似，所以没有太大比较的必要吧。

PermissionX最大的优势我觉得在于权限被拒绝时的提醒和处理逻辑，这些据我所知RxPermission好像也没有。
