### ISSUE TITLE
Kotlin 版本问题，我目前是 1.3.72，升级到 1.5.31 的话还要升级 AGP，但是我接入了 Bugly 的 Tinker 热修复，目前Tinker 不支持那么高的AGP

### ISSUE THREAD

**Issue by shrotybin** [guolindev/PermissionX#137]
Kotlin 版本问题，我目前是 1.3.72，升级到跟你一样的版本的话还要升级 AGP，但是我介入了 Bugly 的 Tinker 热修复，目前Tinker 不支持那么高的AGP

`Task :jwcommon:kaptGenerateStubsDebugKotlin
e: /Users/wuhuabin/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.5.31/43331609c7de811fed085e0dfd150874b157c32/kotlin-stdlib-common-1.5.31.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.
e: /Users/wuhuabin/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.5.31/6628d61d0f5603568e72d2d5915d2c034b4f1c55/kotlin-stdlib-1.5.31.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.
e: /Users/wuhuabin/.gradle/caches/transforms-2/files-2.1/ef7d8ec76efa924b0394c187309c2731/permissionx-1.6.1-api.jar!/META-INF/permissionx_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.
/Users/wuhuabin/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib-common/1.5.31/43331609c7de811fed085e0dfd150874b157c32/kotlin-stdlib-common-1.5.31.jar!/META-INF/kotlin-stdlib-common.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.
/Users/wuhuabin/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.5.31/6628d61d0f5603568e72d2d5915d2c034b4f1c55/kotlin-stdlib-1.5.31.jar!/META-INF/kotlin-stdlib.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16
/Users/wuhuabin/.gradle/caches/transforms-2/files-2.1/ef7d8ec76efa924b0394c187309c2731/permissionx-1.6.1-api.jar!/META-INF/permissionx_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.5.1, expected version is 1.1.16.`

**Comment by jingzz1** [comment]
Tinker连官网都没了，Bugly也停止维护快两年了，死抱着Bugly没有好结果

**Comment by guolindev** [comment]
那你可以使用PermissionX 1.5.0版本，1.6.0版本要求Kotlin要升级到1.5以上才行
