### ISSUE TITLE
权限被拒绝，无法再次申请

### ISSUE THREAD

**Issue by GxYuqi** [guolindev/PermissionX#138]
小米 MIX2S，Android 10，定位权限被拒绝，再次申请不弹出窗口

**Comment by guolindev** [comment]
如果是系统魔改的问题，我这边也没有办法解决。
其实这种bug我建议你使用原生的API在你的手机上去申请试试看，如果原生API也有问题，那就和PermissionX无关了，而是手机问题。

**Comment by ccclll1990** [comment]
品牌:Mi11  系统:MIUI12.5.15  同样无法再次申请
