### ISSUE TITLE
Bugly反馈安卓12崩溃 Resources$NotFoundException

### ISSUE THREAD

**Issue by 94zsh** [guolindev/PermissionX#140]
异常进程#线程

com.hyst.oyefit#main(2)

用户 ID

amandawillems0@gmail.com

发生时间

2021-11-08 09:21:37

上报时间

2021-11-08 09:21:37

前后台状态

前台

设备机型

Pixel 3
系统版本

Android 12,level 31

ROM

google/blueline

CPU架构

arm64-v8a

#266002 android.content.res.Resources$NotFoundException
String resource ID #0x0

com.permissionx.guolindev.dialog.DefaultDialog.buildPermissionsLayout(DefaultDialog.kt:10)

1
android.content.res.Resources.getText(Resources.java:444)
2
android.content.res.Resources.getString(Resources.java:537)
3
android.content.Context.getString(Context.java:705)
4
com.permissionx.guolindev.dialog.DefaultDialog.buildPermissionsLayout(DefaultDialog.kt:10)
5
com.permissionx.guolindev.dialog.DefaultDialog.onCreate(DefaultDialog.kt:4)
6
android.app.Dialog.dispatchOnCreate(Dialog.java:424)
7
android.app.Dialog.show(Dialog.java:318)
8
com.permissionx.guolindev.request.PermissionBuilder.e(PermissionBuilder.java:6)
9
com.permissionx.guolindev.request.PermissionBuilder.g(PermissionBuilder.java:2)
10
com.permissionx.guolindev.request.ExplainScope.showRequestReasonDialog(ExplainScope.java:1)
11
com.hyst.oyefit.other.ExtKt$permissionX$1.onExplainReason(Ext.kt:4)
12
com.permissionx.guolindev.request.RequestBackgroundLocationPermission.request(RequestBackgroundLocationPermission.java:10)
13
com.permissionx.guolindev.request.BaseTask.finish(BaseTask.java:2)
14
com.permissionx.guolindev.request.RequestNormalPermissions.finish(RequestNormalPermissions.java:1)
15
com.permissionx.guolindev.request.RequestNormalPermissions.request(RequestNormalPermissions.java:7)
16
com.permissionx.guolindev.request.RequestChain.runTask(RequestChain.java:1)
17
com.permissionx.guolindev.request.PermissionBuilder.request(PermissionBuilder.java:5)
18
com.hyst.oyefit.other.ExtKt.permissionX(Ext.kt:6)
19
com.hyst.oyefit.view.devices.WeatherActivity$initView$2.onCheckedChanged(WeatherActivity.kt:4)

**Comment by wengang187** [comment]
老哥这问题解决了没

**Comment by guolindev** [comment]
看上去有点像是使用旧版PermissionX出现的错误。

PermissionX从1.6.0版本开始支持Android 12系统，如果你使用的是旧版SDK的话，升级到1.6.0版本即可。

**Comment by 94zsh** [comment]
> 看上去有点像是使用旧版PermissionX出现的错误。
> 
> PermissionX从1.6.0版本开始支持Android 12系统，如果你使用的是旧版SDK的话，升级到1.6.0版本即可。

好的谢谢，我更新试下
