### ISSUE TITLE
PermissionMediator这个类用不了了。

### ISSUE THREAD

**Issue by gaohequan** [guolindev/PermissionX#141]
1.6.1版本
PermissionX.init(this).permissions 爆红了。
PermissionMediator类中显示 
// This class file was compiled with different version of Kotlin compiler and can't be decompiled.
//
// Current compiler ABI version is 1.1.16
// File ABI version is 1.5.1

编译环境 gradle:4.1.0  compileSdkVersion 30

**Comment by CodeK1988** [comment]
+1 是java kotlin的问题么？ 大佬

**Comment by CodeK1988** [comment]
@gaohequan 用1.5.0版本吧 java旧项目的话 不过好像只能用到明年2月份？ 到时候升级吧

**Comment by guolindev** [comment]
升级你的Kotlin版本即可解决这个问题
