### ISSUE TITLE
郭婶,希望能把DefaultDialog中的拒绝权限的提示文案抽出,这样自定义Dialog中也能使用

### ISSUE THREAD

**Issue by fatCat2015** [guolindev/PermissionX#146]
郭婶,希望能把DefaultDialog中的拒绝权限的提示文案抽出,这样自定义Dialog中也能使用,~.~
![WX20211117-134555](https://user-images.githubusercontent.com/15773683/142142102-6bc8d148-6e1c-4e9d-b2bc-d26145264350.png)

**Comment by guolindev** [comment]
我没太看懂你的问题，拒绝权限的提示文案抽出，你具体指的是什么文案呢？

**Comment by guolindev** [comment]
暂时先将此问题关闭，等有更多信息提供时可以重新打开，谢谢。
