### ISSUE TITLE
闪退机型：红米 6A

### ISSUE THREAD

**Issue by liuclub** [guolindev/PermissionX#147]
闪退机型：红米 6A
---
在MainActivity的oncreate调用requestPermissions()闪退

`    @SuppressLint("RestrictedApi")
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        binding = ActivityMainBinding.inflate(layoutInflater)
        setContentView(binding.root)
        immersive(Color.TRANSPARENT)

        val navController = findNavController(R.id.nav_host_fragment_activity_main)
        binding.navView.setupWithNavController(navController)

        navController.addOnDestinationChangedListener { _, destination, _ ->
            Log.d("aaa", "destination = ${destination.displayName}")
            when (destination.label) {
                "HomeFragment", "SecondaryFragment", "ThirdFragment", "UserFragment" ->
                    binding.navView.visibility = View.VISIBLE
                else ->
                    binding.navView.visibility = View.GONE
            }
        }

        //TODO 申请权限

//        requestPermissions()

    }
`

`private fun requestPermissions() {
        val permissionList = arrayListOf(
            Manifest.permission.CAMERA,
            Manifest.permission.INTERNET,
            Manifest.permission.ACCESS_COARSE_LOCATION,
            Manifest.permission.ACCESS_FINE_LOCATION,
            Manifest.permission.ACCESS_WIFI_STATE,
            Manifest.permission.CHANGE_WIFI_STATE,
            Manifest.permission.READ_EXTERNAL_STORAGE,
            Manifest.permission.WRITE_EXTERNAL_STORAGE
        )
        PermissionX.init(this)
            .permissions(permissionList)
            .onExplainRequestReason { scope, deniedList ->
                scope.showRequestReasonDialog(
                    deniedList,
                    "核心功能需要这些权限",
                    "确定",
                    "取消"
                )
            }
//            .onForwardToSettings { scope, deniedList ->
//                scope.showForwardToSettingsDialog(
//                    deniedList,
//                    "您需要在“设置”中手动授予必要的权限",
//                    "确定",
//                    "取消"
//                )
//            }
            .request { allGranted, _, deniedList ->
                if (allGranted) {
//                    Toast.makeText(
//                        requireContext(),
//                        "所有权限被允许",
//                        Toast.LENGTH_LONG
//                    ).show()
                    onBackPressed()
                } else {
                    Toast.makeText(
                        this,
                        "下列权限被拒绝: $deniedList",
                        Toast.LENGTH_LONG
                    ).show()
                }
            }

    }`

**Comment by guolindev** [comment]
请问具体闪退的日志是什么？

**Comment by guolindev** [comment]
暂时先将此问题关闭，等有更多信息提供时可以重新打开，谢谢。
