### ISSUE TITLE
新版本用了这个库，在登录页请求权限的时候新增了大量奔溃：Fatal Exception: java.lang.IllegalStateException Operation cannot be started before fragment is in created state

### ISSUE THREAD

**Issue by xxf32012991** [guolindev/PermissionX#148]
androidx.fragment.app.Fragment$9.launch (Fragment.java:3507)
androidx.activity.result.ActivityResultLauncher.launch (ActivityResultLauncher.java:47)
com.permissionx.guolindev.request.InvisibleFragment.requestNow (InvisibleFragment.java:110)
com.permissionx.guolindev.request.PermissionBuilder.requestNow (PermissionBuilder.java:402)
com.permissionx.guolindev.request.RequestNormalPermissions.request (RequestNormalPermissions.java:53)
com.permissionx.guolindev.request.RequestChain.runTask$permissionx_release (RequestChain.java:51)
com.permissionx.guolindev.request.PermissionBuilder.request (PermissionBuilder.java:262)
com.live.honey.module.login.LoginActivity.requestWritePermission (LoginActivity.java:201)
com.live.honey.module.login.LoginActivity.access$requestWritePermission (LoginActivity.java:53)
com.live.honey.module.login.LoginActivity$requestPermission$1.onResult (LoginActivity.java:194)
com.permissionx.guolindev.request.BaseTask.finish (BaseTask.java:103)
com.permissionx.guolindev.request.RequestInstallPackagesPermission.request (RequestInstallPackagesPermission.java:54)
com.permissionx.guolindev.request.BaseTask.finish (BaseTask.java:54)
com.permissionx.guolindev.request.RequestManageExternalStoragePermission.request (RequestManageExternalStoragePermission.java:54)
com.permissionx.guolindev.request.BaseTask.finish (BaseTask.java:54)
com.permissionx.guolindev.request.RequestWriteSettingsPermission.request (RequestWriteSettingsPermission.java:61)
com.permissionx.guolindev.request.BaseTask.finish (BaseTask.java:54)
com.permissionx.guolindev.request.RequestSystemAlertWindowPermission.request (RequestSystemAlertWindowPermission.java:61)
com.permissionx.guolindev.request.BaseTask.finish (BaseTask.java:54)
com.permissionx.guolindev.request.RequestBackgroundLocationPermission.request (RequestBackgroundLocationPermission.java:62)
com.permissionx.guolindev.request.BaseTask.finish (BaseTask.java:54)
com.permissionx.guolindev.request.RequestNormalPermissions.request (RequestNormalPermissions.java:39)
com.permissionx.guolindev.request.RequestChain.runTask$permissionx_release (RequestChain.java:51)
com.permissionx.guolindev.request.PermissionBuilder.request (PermissionBuilder.java:262)
com.live.honey.module.login.LoginActivity.requestPermission (LoginActivity.java:193)
com.live.honey.module.login.LoginActivity.access$requestPermission (LoginActivity.java:53)
com.live.honey.module.login.LoginActivity$checkAppSign$1.onSuccess (LoginActivity.java:134)
com.live.honey.module.login.LoginActivity$checkAppSign$1.onSuccess (LoginActivity.java:123)
com.xyao.core.api.base.BaseRequest.performSuccess (BaseRequest.java:389)
com.xyao.core.api.base.BaseRequest$2.run (BaseRequest.java:377)
android.os.Handler.handleCallback (Handler.java:809)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:166)
android.app.ActivityThread.main (ActivityThread.java:7555)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run (RuntimeInit.java:469)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:963)

**Comment by xxf32012991** [comment]
大佬，这玩意使用还有什么别的需要注意的点吗？

**Comment by LFWheel** [comment]
> 

我把源码中添加InvisibleFragment部分的代码，commitAllowStateLoss改成了commitNow，就没这问题了

**Comment by SaltedFish-Extreme** [comment]
> 大佬，这玩意还有什么需要注意的点吗？

可以试试轮子哥的[权限框架](https://gitee.com/getActivity/XXPermissions)，我自己也参考郭霖的这个写了一个[权限框架](https://github.com/SaltedFish-Extreme/PermissionX)，出现这个问题主要是因为是在创建fragment之后才申请的权限，我就改成创建之前先申请了，可以参照一下😉

**Comment by guolindev** [comment]
此问题已修复，升级到1.6.2版本即可。

**Comment by castlong** [comment]
我是1.7.1 的版本好像还有这个问题

**Comment by castlong** [comment]
目前不确定是不是 PermissionX引起的 ，但是堆栈信息包含

**Comment by laibinzhi** [comment]
1.7.1 的版本好像还有这个问题+1
