### ISSUE TITLE
@RequiresPermission注解的方法在使用PermissionX申请权限依然报红色

### ISSUE THREAD

**Issue by Straosp** [guolindev/PermissionX#150]
#### 方法使用@RequiresPermission注册，在调用的地方会必须先申请权限
```java
@RequiresPermission(anyOf = {"android.permission.ACCESS_FINE_LOCATION"})
    void requestLocationUpdates() throws Exception;
```

#### 但使用PermissionX申请权限并写在同意的逻辑里面的时候，此方法依然会报红 ，显示未申请权限  是否有方法让调用处不报红呢？

**Comment by Straosp** [comment]
![报红示例](https://user-images.githubusercontent.com/24213421/144203532-0cd34090-57c9-40cd-8f0a-96b412b1b74a.png)

**Comment by guolindev** [comment]
感谢建议，但是我查询了各种方法都没能实现这个功能，看上去这是Google第一方编译器配合第一方的API实现的语法检查功能，第三方的API编译器检测不到，非常遗憾应该是实现不了的。
