### ISSUE TITLE
录音权限检测异常

### ISSUE THREAD

**Issue by hxy493045049** [guolindev/PermissionX#152]
现象: Manifest.permission.RECORD_AUDIO 在部分手机中未授权, 但是回调中显示已授权

手机型号   
    1. vivo x9i,   android 7.1.2,  rom: Funtouch OS_3.1,  
    2. 锤子
    
描述详情:                  
    1. 当权限在manifest中申明时, 调用PermissionX申请权限, 然后点击拒绝, 这是回调的allGranted显示true,
    2. 如果不在manifest中申明, 则显示正常, 拒绝后回调返回false
    3. 抛除PermissionX直接调用系统api , ContextCompat.checkSelfPermission 
           - 已在manifest中申明, 返回 0  (PackageManager.PERMISSION_GRANTED) 
           - 未在manifest中申明, 返回 -1  (PackageManager.PERMISSION_DENIED)
    4. 在高版本手机中行为正常(android 10),  必须得在manifest中申明, 否则无法申请, 拒绝后回调返回false

猜想, 可能国内厂商rom有问题? 需要做版本适配?

```kotlin 
PermissionX.init(this)
                .permissions(android.Manifest.permission.RECORD_AUDIO)
                .explainReasonBeforeRequest()
                .onExplainRequestReason { scope, deniedList ->
                    scope.showRequestReasonDialog(deniedList, "获取录音权限", "确定", "取消")
                }
                .onForwardToSettings { scope, deniedList ->
                    scope.showForwardToSettingsDialog(
                        deniedList, "您需要去应用程序设置当中手动开启",
                        "去设置", "取消"
                    )
                }
                .request { allGranted, grantedList, deniedList ->
                    if (allGranted) {
                        Log.e("FirstFragment", "")
                    } else {
                        Log.e("FirstFragment", "")
                    }
                }`

**Comment by tmx0456** [comment]
我一个锤子和oppo出现了这个问题，请问你改好了么？怎么处理的

**Comment by guolindev** [comment]
也就是说，用系统api去判断和PermissionX得到的是一样的结果对吧？

这种情况其实就是运行时权限被手机厂商魔改了，原则上不需要处理，因为手机厂商希望就是这个样子。

我的猜测是，录音权限手机厂商不想让你提前申请，然后后面就可以随便使用录音功能，而是每次调用录音API的时候，手机厂商会弹一个自己的权限框给用户，告诉用户你正在使用录音功能。

所以厂商有这样一个自己的机制，就不需要再去请求系统的录音权限了，因此不管你是点了同意还是拒绝，系统的API都会返回true。

大概就是这样一个原因。
