### ISSUE TITLE
onForwardToSettings的dialog点击确定跳转后如果没有手动开启权限返回，还会再走一遍onForwardToSettings

### ISSUE THREAD

**Issue by fansangg** [guolindev/PermissionX#155]

**Comment by fansangg** [comment]
除了自己给标记，框架方面有方法规避次情况吗？

**Comment by guolindev** [comment]
这种情况下会视为用户拒绝了一次权限请求，所以会再走一遍onForwardToSettings 回调，这是合理的逻辑。
但是框架是不会告诉你这是第几次被用户拒绝的，如果有统计或逻辑的必要，可能确实得自己加标记了。
