### ISSUE TITLE
请问控制勿扰模式的权限如何申请

### ISSUE THREAD

**Issue by rockzhouchina** [guolindev/PermissionX#157]
申请   Manifest.permission.ACCESS_NOTIFICATION_POLICY,   之后还是无法控制勿扰
 
NotificationManager mNotificationManager = (NotificationManager)getSystemService(Context.NOTIFICATION_SERVICE);
if (!mNotificationManager.isNotificationPolicyAccessGranted()) {
    // 发现没有权限
}

**Comment by guolindev** [comment]
PermissionX暂时还不支持申请这个权限，特殊权限杂而繁多，而且每个特殊权限都需要单独写code去支持，没有批量统一的写法，所以PermissionX现在只能支持几个最常用的特殊权限申请，详情可以参考这篇文章，谢谢 https://blog.csdn.net/guolin_blog/article/details/119055926
