### ISSUE TITLE
request result allGranted issue

### ISSUE THREAD

**Issue by frengky-sinaga** [guolindev/PermissionX#159]
allGranted will return true even if permissions are not allowed after init called several times in a row.

To do actions after permissions are granted, I work around it by comparing grantedList and permissionList.

**Comment by lyl21** [comment]
yes ， I also use this approach

**Comment by qlang122** [comment]
同样的问题，测试小米5s手机，8.0系统，其他手机也有同样问题。请求的时候，手机的权限窗还没弹出来，回调就已经先回调true了

**Comment by NByida** [comment]
>这种情况我遇到过，是你的activity有问题。
当你传入的activity不是当前运行的activity时，就会先回调true，换成当前activity就好了

**Comment by NByida** [comment]
>这种情况我遇到过，是你的activity有问题。
当你传入的activity不是当前运行的activity时，就会先回调true，换成当前activity就好了

**Comment by cristianrabadiaimbox** [comment]
and do you have any solution?

Because not even using what they put above the library does that type of request well

**Comment by NByida** [comment]
`    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)

        setContentView(R.layout.test_rtc_activity)
        PermissionX.init(this)
            .permissions(
                android.Manifest.permission.CAMERA,
                android.Manifest.permission.ACCESS_FINE_LOCATION,
                android.Manifest.permission.RECORD_AUDIO,
                android.Manifest.permission.WRITE_EXTERNAL_STORAGE
            )`
dont use api like this after oncreate(),you cant  use a handler to postdelay,like this
`
    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.test_rtc_activity)
        Handler().postDelayed({
            PermissionX.init(this)
                .permissions(
                    android.Manifest.permission.CAMERA
                )                
        },1000)
`
or just request perm again if grantedList.size ==0,like this
`

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
//        BeautyHelperManager.initHelper()
        setContentView(R.layout.test_rtc_activity)
//        AgoraApiManager.checkAndCreateEngine(this)
        PermissionX.init(this)
            .permissions(
                android.Manifest.permission.CAMERA,
                android.Manifest.permission.ACCESS_FINE_LOCATION,
                android.Manifest.permission.RECORD_AUDIO,
                android.Manifest.permission.WRITE_EXTERNAL_STORAGE
            )
            .request { allGranted, gList, dList ->
                if (allGranted) {
                    if(dList.size==0){
                        requestRoomPermission({
                            LogUtils.i(TAG,"invoke allGranted2")
                            "已授权".toast()},{
                            LogUtils.i(TAG,"invoke not allGranted2")
                            "未授权".toast()})
                    }
                    LogUtils.i(TAG,"invoke allGranted------gList:${gList.size}")
                }else{
                    LogUtils.i(TAG,"invoke not allGranted------dList:${dList.size}")
                }
            }
    }


    fun requestRoomPermission(
        onGranted: () -> Unit,
        onDenieded: (deniedList: List<String>?) -> Unit = {}
    ) {
        PermissionX
            .init(this)
            .permissions(
                android.Manifest.permission.CAMERA, android.Manifest.permission.ACCESS_FINE_LOCATION, android.Manifest.permission.RECORD_AUDIO, android.Manifest.permission.WRITE_EXTERNAL_STORAGE
            )
            .request { allGranted, _, deniedList ->
                if (allGranted) {
                    try {
                        LogUtils.i(TAG,"allGranted2")
                        onGranted.invoke()
                    } catch (e: Exception) {
                        LogUtils.exceptionStackTrace(TAG, e)
                    }
                } else {
                    LogUtils.i(TAG,"not allGranted2")

                    if (!deniedList.isNullOrEmpty()) {
                        PromptUtils.showToast("我们需要${deniedList[0]}权限进房")
                    }
                    LogUtils.exceptionStackTrace(TAG, Exception("授权后再开播"))
                    onDenieded.invoke(deniedList)
                }
            }
    }

`

**Comment by cristianrabadiaimbox** [comment]
I am trying what you have put but I continue with the problem that the personalized message that I have for when they do not accept the messages before the permission request skips.

**Comment by frengky-sinaga** [comment]
this is what i do

```kt
private fun checkPerms(
        perms: List<String>,
        context: FragmentActivity,
        onPermissionGranted: () -> Unit
    ) {
        PermissionX.init(context)
            .permissions(perms)
            .onForwardToSettings { scope, deniedList ->
                scope.showForwardToSettingsDialog(
                    deniedList,
                    "You need to allow necessary permissions in Settings manually",
                    "OK",
                    "Cancel"
                )
            }
            .request { _, grantedList, _ ->
                if (isEqual(perms, grantedList)) onPermissionGranted.invoke()
            }
    }
```

```kt
fun <T> isEqual(first: List<T>, second: List<T>): Boolean {
    if (first.size != second.size) return false

    return first.zip(second).all { (x, y) -> x == y }
}
```

**Comment by cristianrabadiaimbox** [comment]
with your solution I have the opposite problem, the dialog does not appear

**Comment by cristianrabadiaimbox** [comment]
the problem now is that it doesn't go into onForwardToSettings and having removed the request check it doesn't do anything until I ask 4-5 times

**Comment by cristianrabadiaimbox** [comment]
My case is the following:
I have an activity and inside a layout.
Every time I click on the layout button I want 2 permissions to be checked.
For the permission request I pass the main activity so it is a single activity.
With onForwardToSettings it does ask me well in android 12 but in previous ones it does not enter this method
