### ISSUE TITLE
建议请求权限的责任链修改

### ISSUE THREAD

**Issue by cuibg** [guolindev/PermissionX#16]
请求权限的责任链建议将所有的Chain都放到一个list中，这样便与理解和操作，这种操作我感觉不是很好
![image](https://user-images.githubusercontent.com/14813243/88877897-2c936180-d259-11ea-8b65-fd8bd8179e9f.png)

**Comment by cuibg** [comment]
这个如果是固定的两个链还好，要是以后有更多的链存在就会出现问题！

**Comment by guolindev** [comment]
不是很明白你在说什么，PermissionX用链来管理权限就是为了解决扩展性问题的。现在两个链分别就是用于请求普通的权限，以及Android 11上的后台定位权限，后面还会再加入更多的链，用于请求一些特性权限。

因为这些权限有各自的特性性，无法放到一起去请求，所以才使用这种链式的任务来管理，可以分批次请求，这是1.2版本中修改的整体架构，更多内容你可以参考这篇文章 https://blog.csdn.net/guolin_blog/article/details/106746958

**Comment by cuibg** [comment]
@guolindev 阅读了下代码，看到您写的链只适合两个，如果以后再加入更多的链，就需要改动挺大的吧！

**Comment by guolindev** [comment]
完全不是这么回事，我不太清楚你怎么理解的。我将权限请求流程设计成链式的任务执行就是为了后期方便扩展。后期有更多链的时候，我只需要新建一个链的任务，在里面加入具体的实现逻辑，然后把链添加到现在的任务链当中即可，不用改动现有的任何逻辑。反倒是以前的设计方式如果后期有新的权限需求，改动会非常大，牵一发而动全身，关于这个问题我在上面的文章链接中都描述的很详细了。

**Comment by cuibg** [comment]
@guolindev ok
