### ISSUE TITLE
鸿蒙2.0.0 会直接走不赋予权限

### ISSUE THREAD

**Issue by dingyizhe996** [guolindev/PermissionX#160]

**Comment by hazzygogogo** [comment]
官方demo都这样，要gg了啊

**Comment by tengdag** [comment]
我在monkey状态下会出现这种情况情况,目前不确定是鸿蒙的问题还是permissionX的问题

**Comment by guolindev** [comment]
很遗憾，我这里没有鸿蒙的手机，实在没办法测试。或许是鸿蒙系统对部分Android API兼容不够好，这种情况或许需要华为那边进行更好的适配才行。
