### ISSUE TITLE
InvisibleFragment.requestManageExternalStoragePermissionNow方法问题

### ISSUE THREAD

**Issue by XuQK** [guolindev/PermissionX#163]
此方法里应该使用”Settings.ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION“，这样可以直接打开对应APP的权限开关页面，而不是打开整个列表去找自己的APP。

**Comment by guolindev** [comment]
感谢建议，非常有道理，已在这条commit中修改 https://github.com/guolindev/PermissionX/commit/172468b987f31ed975de385d1cf7dab2936fe11e
