### ISSUE TITLE
onForwardToSettings的dialog点击确定跳转后如果没有手动开启权限返回 在红米手机上会出现闪屏问题

### ISSUE THREAD

**Issue by yifanLon** [guolindev/PermissionX#165]
经过排查发现 是点击的时候dismiss掉 然后回来重新走了onForwardToSettings show了一下的原因 
为什么要在跳转之前 先dismiss掉呢

**Comment by guolindev** [comment]
这是因为Android的Dialog只要你点了确定或取消按钮，都会自动dismiss掉，想不被dismiss掉反倒是非常的麻烦，甚至是无法实现的。所以就只能按照默认的逻辑先dismiss掉，然后再根据实际权限的开启状态来判断是否要重新弹出dialog了。
