### ISSUE TITLE
感觉过度封装了，弹窗处理不应该交给框架

### ISSUE THREAD

**Issue by wangkai147** [guolindev/PermissionX#168]

**Comment by guolindev** [comment]
弹窗处理可以不交给框架，也可以交给框架的，这是由你自己选择的，你如果觉得过度封闭了，那么完全可以自己去写弹窗相关的逻辑，不用PermissionX提供的就行了，这个不是强制的。

**Comment by wangkai147** [comment]
嗯，刚刚读了一遍源码，学到了很多，谢谢，以后可不敢乱说话了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Lin ***@***.***&gt;; 
发送时间: 2022年4月17日(星期天) 下午3:57
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [guolindev/PermissionX] 感觉过度封装了，弹窗处理不应该交给框架 (Issue #168)





 
弹窗处理可以不交给框架，也可以交给框架的，这是由你自己选择的，你如果觉得过度封闭了，那么完全可以自己去写弹窗相关的逻辑，不用PermissionX提供的就行了，这个不是强制的。
