### ISSUE TITLE
android.content.res.Resources$NotFoundException: String resource ID #0x0

### ISSUE THREAD

**Issue by chenxiaofei910714** [guolindev/PermissionX#173]
手机：oppo reno 4 pro , 版本11的时候是号的，升级到12之后，就开始崩溃了，使用PermissionX1.5版本，升级到1.6版本又好了
  PermissionX.init(this)
                .permissions(Manifest.permission.ACCESS_FINE_LOCATION)
                .explainReasonBeforeRequest()
                .onExplainRequestReason((scope, deniedList) ->
                        scope.showRequestReasonDialog(deniedList,
                                getString(R.string.permissions_location),
                                getString(R.string.text_agree),
                                getString(R.string.text_cancel)
                        ))
                .onForwardToSettings((scope, deniedList) -> scope.showForwardToSettingsDialog(deniedList,
                        getString(R.string.permissions_location_set),
                        getString(R.string.text_go_to),
                        getString(R.string.text_cancel)))
                .request((allGranted, grantedList, deniedList) -> locationGranted(allGranted));

**Comment by guolindev** [comment]
请升级1.6.3版本，已修复此问题
