### ISSUE TITLE
Android12 逻辑判断问题

### ISSUE THREAD

**Issue by shenyunhuan** [guolindev/PermissionX#174]
在DefaultDialog中buildPermissionsLayout方法
条件应该是 currentVersion >= Build.VERSION_CODES.S 
 而不是currentVersion == Build.VERSION_CODES.S 
不然会走permissionMapOnR的集合
BLUETOOTH_CONNECT就不显示权限名称

**Comment by guolindev** [comment]
感谢反馈，但你想说的应该是Android 13会走permissionMapOnR的集合吧，Android 12直接就进currentVersion == Build.VERSION_CODES.S这个条件了。
已在这条commit中修复此问题 https://github.com/guolindev/PermissionX/commit/7af332e89ce7ae71e8a5cde13c32ec2908c3ff5b
