### ISSUE TITLE
关于 ACTION_MANAGE_APP_ALL_FILES_ACCESS_PERMISSION 权限的降级处理

### ISSUE THREAD

**Issue by XuQK** [guolindev/PermissionX#178]
建议打开此权限的方法，做降级处理，找不到此权限的Activity，就找次一级的。
因为发现在某些 Android11+ 机型上，比如：
Galaxy A03 Core - SM-A032F/DS
Android 11 - Kernel 4.14 199-2303091

没有此 Activity，调用必 FC。

**Comment by guolindev** [comment]
感谢建议，已在1.7.1版本中修正了这部分功能。
