### ISSUE TITLE
使用网络权限

### ISSUE THREAD

**Issue by duronggang** [guolindev/PermissionX#179]
小米 手机安装应用后，默认是没有访问网络权限的，得到手机设置里面，手动设置允许联网。魅族 的会提示 是否允许联网，但是 允许的话，还是无限弹框是否允许使用网络，郭神，这个怎么处理呢

**Comment by guolindev** [comment]
网络权限根本就不是运行时权限，这个库也不用是用于申请网络权限的。如果说有些手机还需要去设置里面手动开启联网才能上网，那只能说是这个手机有问题。
