### ISSUE TITLE
PermissionX.init(this).permissions(permissions).request{} 的时候 inRequestFlow 一直是true 就 return 了, If it's already in a request flow, we shouldn't start a new one.

### ISSUE THREAD

**Issue by xiemy1214** [guolindev/PermissionX#185]
activity申请权限
![00](https://user-images.githubusercontent.com/82264481/174014830-441b27a4-aff4-436c-84b0-847c7072624f.png)
 PermissionX.init(this).permissions(permissions).request{} 的时候 inRequestFlow 一直是true 就 return 了, If it's already in a request flow, we shouldn't start a new one.
![01](https://user-images.githubusercontent.com/82264481/174014978-1d0c74ba-b929-4ede-b96c-ec5b29300039.png)

这个问题不是必现, 但是出现后inRequestFlow 一直是true就没有任何回调了
麻烦帮我看一下, 谢谢

**Comment by guolindev** [comment]
请升级1.7.1版本，这个问题已修复，谢谢。
