### ISSUE TITLE
最新版1.6.4权限请求结果android12上没有回调

### ISSUE THREAD

**Issue by ChaseCSB** [guolindev/PermissionX#186]
红米  android12   

implementation 'com.guolindev.permissionx:permissionx:1.6.4'

PermissionX.init(this)
                .permissions(permissions)
                .onExplainRequestReason(new ExplainReasonCallback() {
                    @Override
                    public void onExplainReason(@NonNull ExplainScope scope, @NonNull List<String> deniedList) {
                        String message = "需要您同意以下权限才能正常使用";
                        scope.showRequestReasonDialog(deniedList, message, "允许", "不允许");
                    }
                }).request(new RequestCallback() {
                    @Override
                    public void onResult(boolean allGranted, @NonNull List<String> grantedList, @NonNull List<String> deniedList) {
                        //第一次安装时点击允许或者不允许都不回调这个方法，第二次进入会回调
                        if (allGranted) {
                            toLogin();
                        } else {
                        }
                    }
                });

另外一台android8的手机没问题

**Comment by guolindev** [comment]
请升级1.7.1版本，这个问题已修复，谢谢。
