### ISSUE TITLE
获取授权时如果切换到桌面，再点击进入APP时，授权操作被打断直接执行了 request 这个回调

### ISSUE THREAD

**Issue by main1230** [guolindev/PermissionX#187]
PermissionX版本号： 1.6.4

复现机型：三星  SM-G9500

复现步骤：
APP申请了Manifest.permission.ACCESS_FINE_LOCATION、Manifest.permission.WRITE_EXTERNAL_STORAGE、Manifest.permission.READ_EXTERNAL_STORAGE、Manifest.permission.READ_PHONE_STATE这几个权限，弹出第一个授权时直接点击拒绝并回到手机桌面，之后再点击图标进入APP，Permissionx直接执行了request 方法 并且打印的数据结果为：
```
request：true [] [] false
```

![image](https://user-images.githubusercontent.com/8016668/177081095-bf3f47a9-cd2e-4048-86f7-a474ac1ca06b.png)

测试代码：
```
PermissionX.init(this)
	.permissions(list)
	.onExplainRequestReason((scope, deniedList) -> {
		LogUtils.showLog(TAG, "onExplainRequestReason " + deniedList);

		scope.showRequestReasonDialog(deniedList, "需要开启相关权限", "确定");
	})
	.onForwardToSettings((scope, deniedList) -> {
		LogUtils.showLog(TAG, "onForwardToSettings " + deniedList);

		scope.showForwardToSettingsDialog(deniedList, "需要开启相关权限", "去设置");

	}).request((allGranted, grantedList, deniedList) -> {
		LogUtils.showLog(TAG, "request：allGranted " + allGranted + " " + grantedList + " " + deniedList + " " + Tools.hasAllPermissions(mActivity));
	});
```

**Comment by guolindev** [comment]
我这里本地测试没能复现这个bug。但是从你的现象描述上看，感觉像是Android系统的bug，回到手机桌面，之后再点击图标进入APP，这是比较典型的singleTask的那个问题，所以我比较怀疑你的launcher activity的launchMode应该是设置的singleTask，从而导致从桌面进入的时候不是回到的之前的Activity，而是创建了一个新的Activity。

至于解决方法，比较简单的是把launch mode改成standard应该就可以了。如果有特殊原因必须用singleTask，那么也可以参考这篇文章的解决方案，里面也详细解释了这个bug的原因  https://mp.weixin.qq.com/s?__biz=MzA5MzI3NjE2MA==&mid=2650253197&idx=1&sn=e9986456f709f00fb2d36940e1c18b30&chksm=886356e2bf14dff4aba99ee3035b2be0076fbadd6a1ed8617e7e5f7a2382d2360abb47423d19#rd
