### ISSUE TITLE
希望增加一个回调，每次同意或者拒绝都回调出来，而不是一次性回调出来

### ISSUE THREAD

**Issue by LxzBUG** [guolindev/PermissionX#188]

**Comment by guolindev** [comment]
这个是系统限制，如果你一次性请求多个权限，那么就是会需要权限都处理完了之后一次性回调结果。

如果你想要每请求一个权限就有一个回调出来，那么可以把权限单个申请，等前一个回调的结果出来了再申请下一个权限。
