### ISSUE TITLE
鸿蒙2.0系统权限拒绝一次之后不再重新发起申请

### ISSUE THREAD

**Issue by henkun614** [guolindev/PermissionX#190]
PermissionX.init(this).permissions(permissions)
            .request { allGranted, grantedList, deniedList ->
                if (allGranted) {
                    showDialog()
                } else {
                    toast("您拒绝了以下权限 $deniedList 可能会对您的正常使用造成影响")
                }
            }
拒绝一次之后allGranted就一直都是false

**Comment by guolindev** [comment]
你可以设置上onExplainRequestReason和onForwardToSettings的回调来引导用户开启权限，详细用户请参考主页文档 https://github.com/guolindev/PermissionX
