### ISSUE TITLE
showRequestReasonDialog无法知道点击事件

### ISSUE THREAD

**Issue by LxzBUG** [guolindev/PermissionX#195]
申请后台定位等特殊权限时，应该让用户允许拒绝。但是需要知道点击拒绝按钮，并弹出提示。

添加可供用户明确选择批准或拒绝授予访问权限的按钮。如果用户拒绝授予访问权限，并且这会限制应用体验，请务必告知他们日后如何更改偏好设置（这是Google Play要求的

现在没法监听按钮点击

**Comment by guolindev** [comment]
PermissionX为了简化请求代码是把权限请求流程高度封装的，如果是想要对用户拒绝授权访问权限的时候进行提示，可以在request方法的回调里面统一做处理，主间的流程是不能hook的，不然打断了PermissionX的处理逻辑，后续的权限请求权限就接不上了。

**Comment by guolindev** [comment]
PermissionX为了简化请求代码是把权限请求流程高度封装的，如果是想要对用户拒绝授权访问权限的时候进行提示，可以在request方法的回调里面统一做处理，主间的流程是不能hook的，不然打断了PermissionX的处理逻辑，后续的权限请求权限就接不上了。
