### ISSUE TITLE
Android 12 申请 MANAGE_EXTERNAL_STORAGE直接返回false

### ISSUE THREAD

**Issue by Marx-Hong** [guolindev/PermissionX#197]
测试版本：implementation 'com.guolindev.permissionx:permissionx:1.6.4'
测试代码：if (Build.VERSION.SDK_INT>Build.VERSION_CODES.R) {
            PermissionX.init(this).permissions(Manifest.permission.MANAGE_EXTERNAL_STORAGE).request { allGranted, grantedList, deniedList ->
                Log.e(TAG, "result:$allGranted")
            }
        }
AndroidManifest参考demo：<uses-permission android:name="android.permission.MANAGE_EXTERNAL_STORAGE"
        tools:ignore="ScopedStorage" />

**Comment by guolindev** [comment]
![image](https://user-images.githubusercontent.com/20859208/189921617-da4b54b1-1cdf-4032-a6cd-335f2d2cac91.png)

我用你上面的代码验证是通过的。直接返回false很有可能是你在AndroidManifest.xml文件中没有声明MANAGE_EXTERNAL_STORAGE权限，请再核实一遍，如果还有问题请再重新将这个issue打开。

**Comment by kllkko** [comment]
在小米13 Android14系统上，也是直接false，AndroidManifest.xml文件中已经声明MANAGE_EXTERNAL_STORAGE权限
