### ISSUE TITLE
无法申请Android 12  的 Bluetooth_scan和  bluetooth_connect权限

### ISSUE THREAD

**Issue by rayzeng0221** [guolindev/PermissionX#198]

**Comment by sinduanan** [comment]
老哥 最后使用哪个库了 ？ @rayzeng0221

**Comment by guolindev** [comment]
![image](https://user-images.githubusercontent.com/20859208/189921113-19b33acf-e793-497d-aaf1-3a90a86fe744.png)
本地测试验证可以正常申请这两种权限，没有更多信息佐证无法申请蓝牙权限，视为用法问题。请检测自己的AndroidManifest.xml文件中是否有声明这两个权限。

**Comment by wolongalick** [comment]
虽然能回调,但如果拒绝了的话,不会弹出去设置的弹框
