### ISSUE TITLE
若用户手动设置“禁止”定位权限，则调用onForwardToSettings不会弹出对话框

### ISSUE THREAD

**Issue by zhbzhbzhbz** [guolindev/PermissionX#201]
测试手机：米10Ultra(Android 12)、华为P30 Pro(Hormony OS 2.0.0)
1）如果在弹出对话框询问时，点拒绝或禁止，**会弹出来onForwardToSettings的对话框**
2）但如果在系统设置的权限管理里，**手动设置“拒绝”或者“禁止”**，再次执行到这里时，**就不会弹出任何对话框**
3）如果手动设置成“仅使用期间允许”，就还会弹
```
PermissionX.init(activity)
	.permissions(Manifest.permission.ACCESS_BACKGROUND_LOCATION)
	.onForwardToSettings(new ForwardToSettingsCallback() {
		@Override
		public void onForwardToSettings(@NonNull ForwardScope scope, @NonNull List<String> deniedList) {
			scope.showForwardToSettingsDialog(deniedList, "为减少熄屏后轨迹问题，需点击【权限管理】→【定位】→【始终允许】", "去设置");
		}
	})
	.request((allGranted, grantedList, deniedList) -> {});
```

谢谢郭神~

**Comment by zhbzhbzhbz** [comment]
哦~ 试了下，如果改成`.permissions(Manifest.permission.ACCESS_FINE_LOCATION,Manifest.permission.ACCESS_COARSE_LOCATION,Manifest.permission.ACCESS_BACKGROUND_LOCATION)` 就没问题了

**Comment by guolindev** [comment]
因为ACCESS_BACKGROUND_LOCATION不能单独申请，而是一定要有ACCESS_FINE_LOCATION或ACCESS_COARSE_LOCATION的情况下再申请ACCESS_BACKGROUND_LOCATION才有用。

可以参考我这篇文章的讲解  https://guolin.blog.csdn.net/article/details/106746958
