### ISSUE TITLE
升级到1.7.1后，报有类重复的错误

### ISSUE THREAD

**Issue by qianshengta** [guolindev/PermissionX#204]
Duplicate class androidx.lifecycle.ViewModelLazy found in modules jetified-lifecycle-viewmodel-ktx-2.3.1-runtime (androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1) and lifecycle-viewmodel-2.5.0-runtime (androidx.lifecycle:lifecycle-viewmodel:2.5.0)
Duplicate class androidx.lifecycle.ViewTreeViewModelKt found in modules jetified-lifecycle-viewmodel-ktx-2.3.1-runtime (androidx.lifecycle:lifecycle-viewmodel-ktx:2.3.1) and lifecycle-viewmodel-2.5.0-runtime (androidx.lifecycle:lifecycle-viewmodel:2.5.0)

**Comment by guolindev** [comment]
可能是因为你的项目中依赖的ktx版本比较老，和PermissionX不匹配导致的，建议升级一下，从错误提示上看，将ktx从2.3.1升级到2.5.0应该就可以了。

**Comment by qianshengta** [comment]
正解
