### ISSUE TITLE
jetified-permissionx-1.7.1-api.jar!/META-INF/permissionx_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.

### ISSUE THREAD

**Issue by oooo7777777** [guolindev/PermissionX#206]
打包的时候 出现如下错误，请问如何解决
/Users/merach/Library/Java/JavaVirtualMachines/corretto-1.8.0_312/Contents/Home/caches/transforms-3/b7693fdafb9e33b0ae2b7d45f9a8e62d/transformed/jetified-permissionx-1.7.1-api.jar!/META-INF/permissionx_release.kotlin_module: Module was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.7.1, expected version is 1.5.1.

**Comment by guolindev** [comment]
这是你的项目使用的Kotlin版本比较老，和PermissionX中的版本不匹配导致的错误，建议将Kotlin版本升级到最新，就不会再有这个错了。
