### ISSUE TITLE
安卓13通知权限跳转

### ISSUE THREAD

**Issue by jzh1996** [guolindev/PermissionX#207]
如果是申请Manifest.permission.POST_NOTIFICATIONS。可以把showForwardToSettingsDialog弹窗的允许按钮的点击事件直接跳转应用的通知开启页面吗。

**Comment by guolindev** [comment]
不可以，Android 13 POST_NOTIFICATIONS被列为了运行时权限，就得按照运行时权限的规则去申请了。

**Comment by jzh1996** [comment]
我的意思是按照运行时权限申请时，点击“去开启”直接跳转到通知开关页面而不是应用设置页面
![image](https://user-images.githubusercontent.com/40649610/196575208-3c33ce94-053e-4476-810c-d034017b7a9f.png)
