### ISSUE TITLE
拒绝后没有走回调

### ISSUE THREAD

**Issue by charmeleon2** [guolindev/PermissionX#210]
permissionX 1.6
手机 小米android 12   / 荣耀android 10
         PermissionX.init(this)
                .permissions(Manifest.permission.RECORD_AUDIO)
                .request { allGranted, grantedList, deniedList ->
                    LogUtils.wTag("publish","$allGranted   $grantedList    $deniedList")
                    if (allGranted) {
                        toast("所有申请的权限都已通过")
                        LogUtils.wTag("publishstate","所有申请的权限都已通过")
                    } else {
                        toast("您拒绝了如下权限：$deniedList")
                        LogUtils.wTag("publishstate","您拒绝了如下权限：$deniedList")
                    }
                }
第一次无论拒绝与否都不会走回调，拒绝的话第二次也不会走回调，第二次以后只有全部通过才会走回调
升级到1.7.1版本也有这个问题（不过1.7.1我是通过本地依赖，修改了androidx.appcompat:appcompat版本为1.3.1，不知道时候会有影响）

**Comment by charmeleon2** [comment]
没事了，是因为之前基类没有调用 super.onRequestPermissionsResult

**Comment by whatisjava** [comment]
> 没事了，是因为之前基类没有调用 super.onRequestPermissionsResult

您好，这个是什么意思？哪里还需要调用这个方法？
