### ISSUE TITLE
希望增加支持在一个权限申请回调里面接着申请另外一个权限的功能

### ISSUE THREAD

**Issue by 523931340** [guolindev/PermissionX#218]
https://github.com/guolindev/PermissionX/issues/188

这个是系统限制，如果你一次性请求多个权限，那么就是会需要权限都处理完了之后一次性回调结果。

如果你想要每请求一个权限就有一个回调出来，那么可以把权限单个申请，等前一个回调的结果出来了再申请下一个权限。

==========================================================
现在权限合规一般需要一个权限申请同时对应显示一个说明该权限的弹窗，如果有两个权限同时需要申请，我现在是在第一个权限申请完的回调里面接着申请另外一个权限，我发现第二个权限申请的回调无法接收到了。通过了解源码，发现第一个权限申请完后，这个权限责任链全部完成了，会先回调onResult，然后再endReuest，会导致第二个权限申请后，对应的InvisibleFrgament在endRequest里面被移除了，导致第二个权限回调无反应，当然这个需求也是很奇葩的

**Comment by yongzhenzou** [comment]
我觉得这是 permissionX需要解决的一个问题，不是需求奇葩。目前有些权限请求已经不支持同时请求了，比如说 后台获取定位权限必须要有普通定位权限，自然想到先申请普通权限然后在回调中申请后台定位权限。结果就是首次申请后台定位权限没有回调。
