### ISSUE TITLE
使用explainReasonBeforeRequest后拒绝权限后如何使弹窗消失

### ISSUE THREAD

**Issue by charmeleon2** [guolindev/PermissionX#220]
版本1.7.1
使用explainReasonBeforeRequest在申请权限前出现提示弹窗，点同意，出现系统申请弹窗，点取消，回来后提示弹窗还继续保留，怎样写可以在拒绝权限后使提示弹窗也消失
` PermissionX.init(this).permissions(Manifest.permission.CAMERA)
                        .explainReasonBeforeRequest()
                        .onExplainRequestReason { scope, deniedList ->
                            scope.showRequestReasonDialog(
                                DefaultDialog(this, listOf(Manifest.permission.CAMER),
                                    "需要相机限才能使用功能",
                                    "确认",
                                    "取消",
                                    Color.RED,
                                    Color.RED
                                )
                            )
                        }
                        .onForwardToSettings { scope, deniedList ->
                            scope.showForwardToSettingsDialog(
                                DefaultDialog(this, listOf(Manifest.permission.CAMERA),
                                    "APP没有相机权限，你可以在设置中开启",
                                    "确认",
                                    "取消",
                                    Color.RED,
                                   Color.RED
                                )
                            )
                        }
                        .request { allGranted, grantedList, deniedList ->
                            if (allGranted) {
                               
                            }
                        }`

**Comment by haoshiwei** [comment]
有解决方案了吗

**Comment by CodeK1988** [comment]
PermissionX.init(fragmentActivity).permissions(*permissions) 返回的可以调对应的dialog对象 @haoshiwei
