### ISSUE TITLE
WRITE_SETTINGS这个权限已经手动设置允许，但回调里面却显示拒绝

### ISSUE THREAD

**Issue by feng-jun-dev** [guolindev/PermissionX#23]

**Comment by guolindev** [comment]
WRITE_SETTINGS这个权限并非是运行时权限，而是另外一种更加特殊的权限，由于特殊权限的请求方式不一样，目前PermissionX还未对特殊权限进行支持。

目前预计会在1.5.0版本当中对特殊权限进行支持，到时我会再来更新这个issue。

**Comment by wtyn** [comment]
首先运行通过所有权限，然后在设置-》权限管理中，拒绝相机权限。再运行app，仍然会显示通过了所有权限。

**Comment by liqvip** [comment]
我也遇到这个问题，WRITE_SETTINGS属于系统权限，即是否允许修改系统设置，存在如下问题：
1. 弹窗不显示权限名称
2. 手动设置允许后，回调仍然显示拒绝
3. 点击取消，回调request方法中的拒绝列表，特殊权限仍然存在。

**Comment by guolindev** [comment]
1.5.0版本已支持WRITE_SETTINGS权限，详情请参考 https://guolin.blog.csdn.net/article/details/119055926
