### ISSUE TITLE
360手机N6 Pro 检测不了权限

### ISSUE THREAD

**Issue by EdifierX** [guolindev/PermissionX#24]
没弹授权的框
![device-2020-09-15-111002](https://user-images.githubusercontent.com/26271167/93161049-4bd04a80-f744-11ea-9b67-6e735c9148bc.png)
![device-2020-09-15-111101](https://user-images.githubusercontent.com/26271167/93161056-525ec200-f744-11ea-8542-8779be6a9171.png)
![device-2020-09-15-111122](https://user-images.githubusercontent.com/26271167/93161063-55f24900-f744-11ea-9dcb-40e4ac2f51bf.png)

**Comment by guolindev** [comment]
PermissionX只在Android标准API上做封装，不针对国产手机特珠情况进行订制。

建议你可以使用一下Android标准的请求权限API在360这台手机上试试看，是不是也有同样的情况，如果标准API可以工作，而PermissionX不行，那么请再重新open这个issue，我再来具体查看下问题原因。

**Comment by EdifierX** [comment]
> PermissionX只在Android标准API上做封装，不针对国产手机特珠情况进行订制。
> 
> 建议你可以使用一下Android标准的请求权限API在360这台手机上试试看，是不是也有同样的情况，如果标准API可以工作，而PermissionX不行，那么请再重新open这个issue，我再来具体查看下问题原因。

目前我用的就是标准API，可以正常工作。PermissionX不行。

**Comment by guolindev** [comment]
可以用PermissionX.isGranted()这个API来检查看看你申请的这几个权限有没有授权成功呢？

**Comment by EdifierX** [comment]
> 可以用PermissionX.isGranted()这个API来检查看看你申请的这几个权限有没有授权成功呢？

神奇，一直返回true... isGranted()也是用checkPermission的API。就这台360N6手机有问题，我用一加7T正常返回false。

**Comment by guolindev** [comment]
如果这样的话，你用标准的API去请求权限应该也是会有问题的吧？

**Comment by guolindev** [comment]
由于长时间没有回复，此问题暂时关闭，如果后续还有问题请再重新打开。
