### ISSUE TITLE
Android 14权限适配

### ISSUE THREAD

**Issue by jiangshufeng** [guolindev/PermissionX#257]
如何适配 READ_MEDIA_VISUAL_USER_SELECTED

**Comment by zhidawu** [comment]
你这也太早了8

**Comment by jiangshufeng** [comment]
已经开始了呢，



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月25日(周五) 上午10:28
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [guolindev/PermissionX] Android 14权限适配 (Issue #257)




 
你这也太早了8

**Comment by ZhangSir99993** [comment]
可以开始行动了

**Comment by guolindev** [comment]
1.8.0版本开始支持READ_MEDIA_VISUAL_USER_SELECTED权限

```
dependencies {
    implementation 'com.guolindev.permissionx:permissionx:1.8.0'
}
```
