### ISSUE TITLE
【建议】PermissionX 和 kotlin 版本关联，建议文档里添加版本对应说明

### ISSUE THREAD

**Issue by ChinaStyle812** [guolindev/PermissionX#26]
因为PermissionX依赖特定的kotlin版本，可能出现引入的PermissionX所依赖的kotlin版本和当前工程已经在用的kotlin版本不一致，导致编译失败，出现 **Cause: duplicate entry: module-info.class** 问题。
比如我当前使用的kotlin版本为1.3.72，引入1.4.0版本的permissionx，就出现了上面的问题。而kotlin版本又和gradle插件乃至Android Studio版本都一定关联，所以有时候还不能通过简单地修改一下使用的kotlin版本来解决。

建议郭神在文档里添加版本对应说明，比如工程使用什么版本的kotlin时，应该使用哪个版本的permissionx。虽然对有经验的开发者来说，不是特别难解决的问题，但我觉得对比较初级的朋友们来说会更友好一点。仅仅是一个建议。

**Comment by ff-frida** [comment]
packagingOptions {
      
        exclude 'META-INF/*.kotlin_module'
    }

遇到同样的问题，配置文件增加这个就可以了。

**Comment by guolindev** [comment]
奇怪的是，我想办法去重现这个问题，新建了一个使用1.3.72的kotlin版本的项目，并引入1.4.0版本的permissionx，但是却未能重现这个问题，有没有什么必现的方法吗？

**Comment by ChinaStyle812** [comment]
> 奇怪的是，我想办法去重现这个问题，新建了一个使用1.3.72的kotlin版本的项目，并引入1.4.0版本的permissionx，但是却未能重现这个问题，有没有什么必现的方法吗？

是我草率了，验证不够严谨。简单demo里1.3.72版本的kotlin+1.4.0版本的permissionx确实不会有问题。我这里的问题出在同时引入1.4.0版本的permissionx和一些其他第三方库和插件，然后尝试将permissionx版本降为1.3.0，编译就OK了，没来得及做其他验证。是其他gradle插件在transform处理过程中报错了，不算是permissionx的问题。

**Comment by hehuiran** [comment]
Class 'kotlin.jvm.Throws' was compiled with an incompatible version of Kotlin. The binary version of its metadata is 1.4.0, expected version is 1.1.9.
The class is loaded from C:/Users/Administrator/.gradle/caches/modules-2/files-2.1/org.jetbrains.kotlin/kotlin-stdlib/1.4.0/63e75298e93d4ae0b299bb869cf0c627196f8843/kotlin-stdlib-1.4.0.jar!/kotlin/jvm/Throws.class

**Comment by hehuiran** [comment]
这是我用1.4.0的permissionx出现的问题，编译通不过
