### ISSUE TITLE
Android 14

### ISSUE THREAD

**Issue by AngelinaFedorova** [guolindev/PermissionX#277]
Hello, will the library be updated to Android 14? 
New permissions have appeared and now they cannot be processed using the library. For example android.permission.READ_MEDIA_VISUAL_USER_SELECTED

**Comment by akaraul** [comment]
@guolindev it's problem for me also. Please update library if possible

**Comment by ZhangSir99993** [comment]
+1

**Comment by AndroidLMY** [comment]
+1

**Comment by qs991011** [comment]
要烂尾了吗

**Comment by guolindev** [comment]
Please try the 1.8.0 version for the READ_MEDIA_VISUAL_USER_SELECTED permission.

```
dependencies {
    implementation 'com.guolindev.permissionx:permissionx:1.8.0'
}
```
