### ISSUE TITLE
1.4.0版本依赖添加导致多语言资源文件切换失效

### ISSUE THREAD

**Issue by windyziheng** [guolindev/PermissionX#28]
郭神，在添加1.4.0版本依赖后，我在Activity中重写attachBaseContext方法切换多语言资源文件的方法会失效但没有报错，即Activity级的Resources切换失败，但是Application级的Resources是能成功切换的，说明代码没有问题。
将依赖版本切换回1.3.0版本则没有这个问题，我测试的时候没有使用PermissionX的方法，仅仅添加依赖就会出现这个问题，求解啊

**Comment by guolindev** [comment]
别慌，可能是因为依赖的升级导致的问题，因为PermissionX库中依赖的其他库都比较新，所以可能让你的项目被动升级了。

你能贴一下你是怎么切换多语言资源文件的吗？因为我还不太清楚你具体执行了什么操作。

**Comment by windyziheng** [comment]
`    @Override
    protected void attachBaseContext(Context newBase) {
        Context context = languageWork(newBase);
        super.attachBaseContext(context);
    }

    private Context languageWork(Context context) {
        // 8.0及以上使用createConfigurationContext设置configuration
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            return updateResources(context);
        } else {
            return context;
        }
    }

    private Context updateResources(Context context) {
        Resources resources = context.getResources();
        //这里是从SharedPreferences中拿语言locale，断点调试是能拿到正确值的
        Locale locale = LanguageUtils.getLocale(context);
        if (locale == null) {
            return context;
        }
        Configuration configuration = resources.getConfiguration();
        configuration.setLocale(locale);
        configuration.setLocales(new LocaleList(locale));
        return context.createConfigurationContext(configuration);
    }`

这里是写在Activity基类的代码，整个流程调试下来没有发现有问题 @guolindev

**Comment by guolindev** [comment]
看上去也并没有什么特殊的地方。

我现在能告诉你的信息是，PermissionX 1.4.0会依赖appcompat 1.2.0版本，也就是这个依赖：

`implementation 'androidx.appcompat:appcompat:1.2.0'`

所以只要你升级了1.4.0，也就相当于把appcompat升级到了1.2.0版本，我目前只能怀疑是这个原因导致你资源切换失败了。

要不然你试一下不要引用PermissionX，然后把你本身的appcompat库也升级到1.2.0版本，看看会不会出现同样的问题，如果也会出现，那就可以找到问题原因了。

**Comment by windyziheng** [comment]
> 看上去也并没有什么特殊的地方。
> 
> 我现在能告诉你的信息是，PermissionX 1.4.0会依赖appcompat 1.2.0版本，也就是这个依赖：
> 
> `implementation 'androidx.appcompat:appcompat:1.2.0'`
> 
> 所以只要你升级了1.4.0，也就相当于把appcompat升级到了1.2.0版本，我目前只能怀疑是这个原因导致你资源切换失败了。
> 
> 要不然你试一下不要引用PermissionX，然后把你本身的appcompat库也升级到1.2.0版本，看看会不会出现同样的问题，如果也会出现，那就可以找到问题原因了。

确实是`implementation 'androidx.appcompat:appcompat:1.2.0'`的问题，这个版本还不稳定，网上有人碰到了同样的问题[https://blog.csdn.net/qq_35936174/article/details/108124335](url)
郭神有办法让项目appcompat版本不随PermissionX的版本强制更新吗？

**Comment by guolindev** [comment]
可以的，你用如下方式来引用permissionx就行了。

`
implementation('com.permissionx.guolindev:permissionx:1.4.0') {
    exclude group: 'androidx.appcompat', module: 'appcompat'
}
`

这样permissionx中就不会再依赖appcompat库，gradle会用你自己项目中添加的appcompat的版本。

**Comment by windyziheng** [comment]
Ok，这次完美解决了，谢谢郭神！
