### ISSUE TITLE
Redmi Note3，Android5.0.2，应用权限全部关闭后，申请权限的时候走了成功回调

### ISSUE THREAD

**Issue by hloong** [guolindev/PermissionX#3]
Redmi Note3，Android5.0.2，应用权限全部关闭后，申请权限的时候走了成功回调

**Comment by guolindev** [comment]
Android运行时权限是6.0系统才引入的，5.0的时候并没有运行时权限的API。

你手机上的情况是小米系统自己引入的一套运行时权限系统，它并没有提供一套让开发者适配的API，而是可以不用适配，因为当你进行一些权限敏感的操作时，小米系统会自动弹出权限提示框来让用户进行授权，不用开发者编写额外的代码。

**Comment by hloong** [comment]
我用另外一个AndPermission（https://github.com/yanzhenjie/AndPermission）的开源框架，对方走的是失败的回调
