### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by zhangwenxiang26** [guolindev/PermissionX#30]
java.lang.NullPointerException:Attempt to read from field 'java.util.Set k.n.a.d.e.h' on a null object reference

com.permissionx.guolindev.request.InvisibleFragment.d3(InvisibleFragment.java:1)

com.permissionx.guolindev.request.InvisibleFragment.onRequestPermissionsResult(InvisibleFragment.java:1)

androidx.fragment.app.FragmentActivity.onRequestPermissionsResult(FragmentActivity.java:6)

android.app.Activity.dispatchRequestPermissionsResult(Activity.java:8566)

在引导页请求定位权限，在 onCreated 触发权限请求。

不知道用户怎么操作的，出现空指针。

引导页跟踪生命周期：onCreated ----》onResumed -----》onPaused

机型：

三星 SM G975F  Android 10,level 29

华为 LYA L29      Android 10,level 29

@guolindev

**Comment by guolindev** [comment]
因为代码被混淆了，我从上面的日志当中也没办法定位出来具体空指针在哪里。但是关于空指针的问题之前也有人提出，并且PermissionX已经进行了解决，所以这个要看你具体使用的是哪个版本的PermissionX。

我认为你可以参考一下 https://github.com/guolindev/PermissionX/issues/22 这个issue，它的堆栈信息和你大体有点相似，但是没有被混淆。如果是同样的问题的话，升级一下版本应该就好了。

**Comment by guolindev** [comment]
因为你这个错误估计是线上统计到的，你自己本地可能也复现不出来，所以我先把这个问题关掉了。

如果你升级了版本之后还遇到这个问题，可以再重新提个issue，最好是能把不带混淆的堆栈信息发出来。PermissionX的代码是可以不用混淆的。
