### ISSUE TITLE
Cause: zip file is empty

### ISSUE THREAD

**Issue by ChunmingWu** [guolindev/PermissionX#32]
引入了PermissionX后Studio老是报 Cause: zip file is empty。升级了Studio（4.0.2）和gradle(6.6.1)之后又报No such property: variantConfiguration for class: com.android.build.gradle.internal.variant.ApplicationVariantData。
后来发现PermissionX的commit记录中有一条“Do not upgrade to gradle plugin 4.0 for now.”
遂放弃PermissionX，哭唧唧。

**Comment by guolindev** [comment]
这个问题很奇怪，我自己这边没有遇到过，在网上查也没有查到相关问题的解决方案。

至于commit中的提交记录那个是给我看的，不是给你们看的。之所以有这样一条提交记录，是因为我升级了gradle之后，发现库发布不到jcenter上了，因为我用的bintray-release这个发布插件好像没人维护了，没有对新版的as和gradle做兼容，所以我暂时降回了之前的版本。但这只是影响我发布而言，和你们的项目没关系，你们用as 4.0和gradle6.6都可以正常使用，我都是做过测试的。

至于为什么你的项目引入permissionx就报错，这个我确实也猜不出来，我自己这边测试都是正常的，感觉应该是和你的项目某处细节有冲突。你可以自己建个空项目，把所有的版本都升到最新，然后引入permissionx看看有没有问题。

**Comment by zhao8816** [comment]
在我的项目中同样出现这样的问题（as 4.0.1、gradle6.1.1），使用1.3.0没问题，升级到1.4.0，编译就会提示Cause: zip file is empty。应该是跟我项目中有冲突，因为新建空项目是可以使用permissionx-1.4.0的，类似这样的问题(空项目demo好使，集成到自己项目就各种问题)不只遇到一次了，额！研究中...

**Comment by guolindev** [comment]
这个问题还真是奇怪了，由于我这边没法重现，所以我也不知道该从什么地方去查起，如果你能帮我定位到问题的原因，那就太感谢了。

另外，1.3.0到1.4.0除了库自身的代码升级（基本不可能和这个有关系）之外，还有对依赖库进行了升级，比如appcompat库升到了1.2.0的版本，不知是否会和这个有关系。

**Comment by zhao8816** [comment]
我妥协了，最终使用“v1.3.0+自定义对话框”的方案。搞了一下午没整明白，由于时间关系(其实是能力不足)就先妥协了。

**Comment by Klien-m** [comment]
我也出现了这样的问题，奇怪的是我按照 @zhao8816  的方法修改版本后，第一次重新编译没有报错，后来第二次编译时就又出现了这个错误。我猜测我这里可能是 aspectjx 导致了这个错误，我在 demo 项目中也因为 aspectjx 出现了这个错误，然后我尝试将 aspectjx 从我的项目中暂时移除，这个问题得到了解决，但具体的原因我暂时还不清楚。

**Comment by liqvip** [comment]
同样遇到这个问题，build无法通过。版本降到1.3即可。

**Comment by guolindev** [comment]
目前PermissionX已经升级到1.5版本，没有收到更多类似反馈，先将此问题关闭，如果还有此问题请再开一个新的bug。
