### ISSUE TITLE
【崩溃BUG】申请两个权限，将其中一个”禁止后不再提醒“，然后去应用设置将被允许的权限也禁止，再返回App直接崩溃

### ISSUE THREAD

**Issue by MapleDS** [guolindev/PermissionX#34]
复现操作：
(1) 点击按钮弹出RequestReasonDialog，点击确定。
(2) 允许存储权限，拒绝相机权限。此时会再次弹出RequestReasonDialog。
(3) 点击确定，然后点击禁止后不再提示。此时会弹出ForwardToSettingsDialog。
(4) 点击确定，然后在应用程序权限设置中禁止存储权限。
(5) 再次返回App，App崩溃。

核心代码如下：
PermissionX.init(this)
                .permissions(Manifest.permission.READ_EXTERNAL_STORAGE,
                        Manifest.permission.WRITE_EXTERNAL_STORAGE,
                        Manifest.permission.CAMERA)
                .explainReasonBeforeRequest()
                .onExplainRequestReason(new ExplainReasonCallback() {
                    @Override
                    public void onExplainReason(ExplainScope scope, List<String> deniedList) {
                        String message = "该功能需要您同意以下权限才能正常使用";
                        scope.showRequestReasonDialog(deniedList, message,
                                "确定", "取消");
                    }
                })
                .onForwardToSettings(new ForwardToSettingsCallback() {
                    @Override
                    public void onForwardToSettings(ForwardScope scope, List<String> deniedList) {
                        scope.showForwardToSettingsDialog(deniedList,
                                "您需要去应用程序设置中手动开启以下权限",
                                "确定", "取消");
                    }
                })
                .request(new RequestCallback() {
                    @Override
                    public void onResult(boolean allGranted, List<String> grantedList, List<String> deniedList) {
                        if (allGranted) {
                        }
                    }
                });

**Comment by guolindev** [comment]
有崩溃的日志吗？

**Comment by MapleDS** [comment]
> 有崩溃的日志吗？

没有，我写了个demo，直接闪退，Logcat看不到错误

**Comment by guolindev** [comment]
额。。那不一定是错误，因为在很多手机上，如果你运行过程中去设置里面关闭了一个权限，系统会把app自动关闭的。

**Comment by MapleDS** [comment]
> 额。。那不一定是错误，因为在很多手机上，如果你运行过程中去设置里面关闭了一个权限，系统会把app自动关闭的。

好像真的是这样，我刚试了QQ，运行中把权限关了QQ也会重启。

**Comment by MapleDS** [comment]
> 额。。那不一定是错误，因为在很多手机上，如果你运行过程中去设置里面关闭了一个权限，系统会把app自动关闭的。



> > 额。。那不一定是错误，因为在很多手机上，如果你运行过程中去设置里面关闭了一个权限，系统会把app自动关闭的。
> 
> 好像真的是这样，我刚试了QQ，运行中把权限关了QQ也会重启。



> 额。。那不一定是错误，因为在很多手机上，如果你运行过程中去设置里面关闭了一个权限，系统会把app自动关闭的。

学习了，谢谢！

**Comment by MapleDS** [comment]
> 额。。那不一定是错误，因为在很多手机上，如果你运行过程中去设置里面关闭了一个权限，系统会把app自动关闭的。

学习了，谢谢！

**Comment by guolindev** [comment]
恩，绝大部分手机都是这样的，但是也有小部分手机不会重启。所以这部分一般不太做适配，也很难做。

当然如果是崩溃，无论如何都得解决的，这种非崩溃的问题，就可以不用管了。

**Comment by MapleDS** [comment]
嗯嗯
