### ISSUE TITLE
android11权限问题

### ISSUE THREAD

**Issue by zhangyongxiangs** [guolindev/PermissionX#38]
我的三星android11申请位置权限申请不到把targetSdkVersion改到29就可以了，麻烦解答下
private String[] mPermissions = {
            Manifest.permission.READ_PHONE_STATE,
            Manifest.permission.READ_EXTERNAL_STORAGE,
            Manifest.permission.WRITE_EXTERNAL_STORAGE,
            Manifest.permission.CAMERA,
            Manifest.permission.ACCESS_FINE_LOCATION,
            Manifest.permission.ACCESS_COARSE_LOCATION,
            Manifest.permission.ACCESS_BACKGROUND_LOCATION
    };
这是我申请的权限

**Comment by liu-wanshun** [comment]
targetVersion为30的时候，你必须单独申请后台位置权限，而且要在获取前台权限之后，顺序不能乱

**Comment by guolindev** [comment]
关于Android 11的权限变更，我在这篇文章当中有比较详细的讲解，我认为应该可以解决你的问题： https://guolin.blog.csdn.net/article/details/106746958

我暂时先将这个问题关闭，如果上面的文章还是不能解决你的问题的话，请再把这个问题打开。
