### ISSUE TITLE
PermissionX为何不走request？

### ISSUE THREAD

**Issue by wgc123** [guolindev/PermissionX#39]
我添加权限Manifest.permission.SYSTEM_ALERT_WINDOW，允许访问权限后走的是onForwardToSettings()方法，不是走request()方法，如果不添加Manifest.permission.SYSTEM_ALERT_WINDOW权限，就成功，否则失败

**Comment by guolindev** [comment]
SYSTEM_ALERT_WINDOW并不是运行时权限，所以不需要通过PermissionX进行申请。

至于悬浮窗这个功能，目前PermissionX还不支持，计划可能会在下个版本当中支持悬浮窗功能的申请，当然这个并不是SYSTEM_ALERT_WINDOW权限，所以也不是一回事。

**Comment by wgc123** [comment]
谢谢郭神！！

**Comment by guolindev** [comment]
ok，那这个问题先关闭了，至于新版本发布的时候我会在公众号和博客里通知的，也可以watch这个project，有提交时你应该能看到。

**Comment by wgc123** [comment]
好的，谢谢！！
