### ISSUE TITLE
升级到Android Studio 4.0, gradle版本为6.1.1时build失败。

### ISSUE THREAD

**Issue by wixche** [guolindev/PermissionX#4]
错误信息：
Unable to load class 'org.gradle.api.internal.java.usagecontext.LazyConfigurationUsageContext'.
Possible causes for this unexpected error include:
Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
Re-download dependencies and sync project (requires network)

The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
Stop Gradle build processes (requires restart)

Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.

In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by guolindev** [comment]
已修复此问题 https://github.com/guolindev/PermissionX/commit/9db4717d4abd860c3770f9bdeb440c222757f455
