### ISSUE TITLE
呼叫转移权限不能自动获取

### ISSUE THREAD

**Issue by zygzx** [guolindev/PermissionX#41]
安装完软件后，用户确认了所有的权限，但是这个呼叫转移权限，却不能自动打开。必须手动去权限处打开。有什么办法解决么？

![图片](https://user-images.githubusercontent.com/25587544/98748663-1a4ac700-23f5-11eb-895b-8863415a46ac.png)

安卓老版本是可以提醒用户获取的（应该是6.0以下版本）
![图片](https://user-images.githubusercontent.com/25587544/98748920-a230d100-23f5-11eb-978a-d50c33493b62.png)

**Comment by guolindev** [comment]
这个我不是很清楚，你能找到这个呼叫转移权限具体对应的是Android当中的哪个权限名吗？

**Comment by guolindev** [comment]
由于长期没有回复，暂时先将此问题关闭了。
