### ISSUE TITLE
蓝牙权限有问题

### ISSUE THREAD

**Issue by 798146512** [guolindev/PermissionX#42]
请求蓝牙（Manifest.permission.BLUETOOTH）权限的时候，用户还没点击授权或者拒绝，就直接进入request的回调函数

**Comment by 798146512** [comment]
网上查了资料，用系统的权限请求也会出现这种情况，不知道郭神有没有什么好的办法

**Comment by guolindev** [comment]
我去查了一下，蓝牙权限是非运行时权限，也就是说并不需要申请权限，直接就可以使用。

所以你直接写蓝牙的相关代码就能正常运行，专门去请求一下权限反而会出问题。

**Comment by 798146512** [comment]
嗯，就是通过代码去打开蓝牙开关的时候，还是会弹出一个仅授权一次的系统权限框

**Comment by guolindev** [comment]
国产特色，不用理就行了。
