### ISSUE TITLE
Android 11

### ISSUE THREAD

**Issue by sakura-rain-studio** [guolindev/PermissionX#44]
> 是不是没有适配Android11啊，MANAGE_EXTERNAL_STORAGE申请有问题，不弹窗直接拒绝

**Comment by guolindev** [comment]
倒不是说没有适配Android 11，而是没有适配特殊权限，目前Permissionx只支持申请运行时权限，MANAGE_EXTERNAL_STORAGE并不是运行权限。

不过对于常用的特殊权限预计会在下个版本中支持，谢谢关注。

**Comment by hardikamal** [comment]
@guolindev Any update on this?

**Comment by guolindev** [comment]
1.5.0版本已支持MANAGE_EXTERNAL_STORAGE权限，详情请参考 https://guolin.blog.csdn.net/article/details/119055926

**Comment by kevin4dhd** [comment]
no working for me

**Comment by kevin4dhd** [comment]
![image](https://user-images.githubusercontent.com/22886367/152894655-c2c8d3fa-c997-40dd-a743-bceb75e19b76.png)
It always returns false without even displaying the permission screen

**Comment by FongMi** [comment]
1.7.1 Not work too
