### ISSUE TITLE
小米手机在启动页检测短信权限没有效果READ_SMS

### ISSUE THREAD

**Issue by shiner0** [guolindev/PermissionX#45]
启动页不弹出短信权限弹窗 ，进入到首页的时候弹出

**Comment by guolindev** [comment]
这是小米手机问题，和PermissionX无关，你可以用原生的API去试试看在小米手机上请求短信权限，一样也是请求不到的。

**Comment by shiner0** [comment]
有什么其他的办法解决这个问题吗？除了跳转到系统设置页面

**Comment by shiner0** [comment]
> 这是小米手机问题，和PermissionX无关，你可以用原生的API去尝试看在小米手机上请求短信权限，一样也是请求不到的。

有什么其他的办法解决这个问题吗？除了跳转到系统设置页面

**Comment by guolindev** [comment]
不用解决呀，小米这么设置就是不需要你解决的，你就正常写你的代码就行了，一定不会崩，小米会在读短信的那一刻自动弹窗让用户授权，不需要你提前申请。

**Comment by shiner0** [comment]
> 不用解决呀，小米这么设置就是不需要你解决的，你就正常写你的代码就行了，一定不会崩，小米会在读短信的那一刻自动弹窗让用户授权，不需要你提前申请。

这样的话小米手机短信权限 怎么检测用户拒绝的行为

**Comment by guolindev** [comment]
没办法检测，这种就是小米帮你把这个过程封装掉了，如果用户拒绝了权限，代码就不会继续向下运行。完全是系统问题，我的建议是不用在这个方法多做研究，因为所有的app在小米手机上都是一样的，包括微信也得这么处理。

**Comment by shiner0** [comment]
> 没办法检测，这种就是小米帮你把这个过程封装掉了，如果用户拒绝了权限，代码就不会继续向下运行。完全是系统问题，我的建议是不用在这个方法多做研究，因为所有的app在小米手机上都是一样的，包括微信也得这么处理。

好的 谢谢
