### ISSUE TITLE
Exception when requesting permissions without using .explainReasonBeforeRequest()

### ISSUE THREAD

**Issue by IHateSyntaxErrors** [guolindev/PermissionX#47]
I got this exception while trying to request the permissions without using .explainReasonBeforeRequest():
https://pastebin.com/6yFKLxg5

Meaning my code works when I do this:
https://pastebin.com/uBmi6R9m

And gives the crash when I do this:
https://pastebin.com/NDjUGMAs

**Comment by guolindev** [comment]
Well. This is a very interesting issue.

Fragments will have transaction problem when adding a new fragment inside another while the transaction still is processing.

So if we want to avoid this problem, getChildFragmentManager() is one of the solution.

But PermissionX can get the ChildFragmentManager only if you pass the instance of current Fragment to the init() function.

Which means you should write something like this:

```
PermissionX.init(this)
                .permissions(permissions)
```

But your codes use getActivity() to get the Activity instance and pass it to init() function like this:

```
PermissionX.init(getActivity())
                .permissions(permissions)
```

At this time, PermissionX won't know you are requesting the permissions in a Fragment and will use the default getFragmentManager(). Then the transaction problem happened.

So I think now you know why this problem happened and how to solve it.

**Comment by IHateSyntaxErrors** [comment]
Thank you for your feedback,

I have been able to solve this problem by getting the fragment with the tag I had set.
```java
PermissionX.init(getFragmentManager().findFragmentByTag("FRAGMENT_HOME"))
                .permissions(permissions)
```

I hope this helps if someone has the same problem, also make sure to give it a tag when you add the fragment like this.
```java
final FragmentManager fragmentManager = getSupportFragmentManager();
final Fragment fragmentHome = new HomeFragment();
fragmentManager.beginTransaction()
                .add(R.id.fragment_container, fragmentHome, "FRAGMENT_HOME")
```

**Comment by guolindev** [comment]
Glad you find a  feasible way. So I will close this issue now.
