### ISSUE TITLE
能否添加自定义权限申请框功能

### ISSUE THREAD

**Issue by woaimi520** [guolindev/PermissionX#49]
郭神 有没有可能添加 自定义权限申请框功能，我在工程里引用了 但是自定义的好像是 授权前的提示框 和 拒绝后的说明框 ，实际申请权限那个dialog 能否也能自定义

**Comment by guolindev** [comment]
这个是不可能的，除非Android系统开放这部分的API，而我完全没有发现Google有这方面的态度。
