### ISSUE TITLE
引入PermissionX使用打包时会出现More than one file was found with OS independent path 'META-INF/library_release.kotlin_module'

### ISSUE THREAD

**Issue by guobinAndroid** [guolindev/PermissionX#5]
很感谢郭神写的库。
上面引起的原因是因为使用Kotlin 会自动创建META-INF/library_release.kotlin_module 文件。可能会和其他库出现冲突。有的解决方案是
android {
    .........
    packagingOptions {
        exclude 'META-INF/library_release.kotlin_module'
   }
}
但是这个对我没作用，因为我本地有一个library库，和你的库名字一样了，然后生成的也一样了，就报错了，我用这种方式的话，会导致项目不能用，我现在把本地的库名字改了，就可以了。
不过这个可以在库上解决根本原因，这样就避免了让每个人都添加排除修复程序：
https://github.com/ChuckerTeam/chucker/issues/134

**Comment by guolindev** [comment]
我还真没遇到这个错误，我这边在Kotlin工程中引用PermissionX库一切都是正常的。按你发的链接上来说，就是要把rootProject.name指定成更复杂的名字是吗？ PermissionX这个名字冲突的概率也很低吧。

**Comment by guolindev** [comment]
另外刚刚更新的这个版本，PermissionX改成用Java实现了，你试试看还会不会和你那边的项目冲突。

**Comment by guobinAndroid** [comment]
Java 不会冲突，我的项目是用kotlin写的，所以会出现冲突，不是PermissionX的名字，是module 的名字是library冲突了。kotlin会自动创建这个META-INF/library_release.kotlin_module文件，郭神，kotlin的方式暂时不同步更新吗？

**Comment by guolindev** [comment]
原来如此，我还真不清楚还有这个坑。

第一个版本用Kotlin做因为还是在以《第三行代码》第16章的内容做扩展，不过用Kotlin写的库只能限定于Kotlin使用，通用性不够好，所以这一版就改成用Java实现了。后面除非是给Kotlin提供专属api的时候会用Kotlin实现，主体功能应该都会用Java来实现。

**Comment by wiztensai** [comment]
still same, i use kotlin
