### ISSUE TITLE
Android 7.1.2不走弹窗

### ISSUE THREAD

**Issue by litaogithub** [guolindev/PermissionX#50]
![image](https://user-images.githubusercontent.com/10986537/101119585-9916d680-3626-11eb-95a6-9b99eb981de9.png)
如图：
默认第一次进来没有走去申请弹窗提示，拒绝禁止提示后也没有走去设置弹窗，并且首次进来会走request回调，allGranted为true
8.0及以上目前看是好的，郭神 帮看下
设备：vivo X9
系统：android 7.1.2

**Comment by guolindev** [comment]
你一共请求了哪些权限呢？

**Comment by litaogithub** [comment]
Manifest.permission.CAMERA
 Manifest.permission.RECORD_AUDIO
相机和麦克风就这2个

**Comment by guolindev** [comment]
vivo X9这台手机，首次进来会走request回调，allGrated为true，你能把grantedList中的内容也打印一下吗？

**Comment by litaogithub** [comment]
![image](https://user-images.githubusercontent.com/10986537/101127508-b0f75600-3638-11eb-9081-aac8472e69f1.png)

**Comment by guolindev** [comment]
那就说明这两个权限都已经授权了呀，不需要再申请了，你可以直接调用摄像头和麦克风的api了。

**Comment by litaogithub** [comment]
权限管理里还是禁止的，页面也没有摄像头画面，说明还是没有权限的

**Comment by guolindev** [comment]
那这个我也不好说了，只能说是手机问题。PermissionX也只是对系统的API做封装，没有权利超越系统的权限去授权。

你可以在vivo X9这台手机上试一下在首次进来的时候用原生api去判断摄像头和麦克风这两个权限是否授权，我相信结果也是一样的。当然如果你测出来不一样的话，那这就是PermissionX的bug了，可以再告诉我。

注：可以用 PermissionX.isGranted()函数来简单地判断一个权限是否已授权，当然也只是对原生api做了层封装而已，授权结果还是取决于系统。

**Comment by litaogithub** [comment]
好的，我在试试 感谢郭神
