### ISSUE TITLE
我想请求联系人的读写权限，回调直接返回的拒绝

### ISSUE THREAD

**Issue by lucers** [guolindev/PermissionX#54]
PermissionX.init(topActivity)
                .permissions(Manifest.permission.READ_CONTACTS, Manifest.permission.WRITE_CONTACTS)
                .request { allGranted, _, deniedList ->
                    if (allGranted) {
                        getLocalContacts()
                    } else {
                        toastMsg.value = "没有权限:${deniedList}"
                        LogUtils.e("Without Permission:${deniedList}")
                    }
                }

**Comment by guolindev** [comment]
deniedList里返回的是什么呢？

**Comment by lucers** [comment]
两个权限都在deniedList中

**Comment by guolindev** [comment]
是不是这两个权限都被永久拒绝过，所以不再申请了，你卸载了应用重装一下再试试。

**Comment by lucers** [comment]
补充。1.4.0版本，华为mate 10，Android 10手机（首次安装，直接返回拒绝）
Nexus 6P Android 8.1手机（重装过，进去直接被拒绝）

**Comment by guolindev** [comment]
如果你只申请Manifest.permission.READ_CONTACTS这一个权限，能正常吗？

**Comment by lucers** [comment]
试了下，不行，我检查下我的手机设置看看

**Comment by guolindev** [comment]
这个还真是有点奇怪了，第一次遇到。因为PermissionX实际上也只是对原生API进行了一层封装，底层还是用的原生API去请求的权限，那么你能直接用原生的方式去请求看看Manifest.permission.READ_CONTACTS这个权限行不行呢？

**Comment by lucers** [comment]
找到问题了，我设置的问题，打扰了，另外发文章做案例的时候，麻烦不要在文章里显示个人信息

**Comment by guolindev** [comment]
我去翻了下之前的文章，发现确实有篇文章当中截图了你提的一个issue，已帮你的名字打码处理。

**Comment by lucers** [comment]
好的，谢谢

**Comment by liaoyong120108** [comment]
请问是哪里设置的问题，我也遇到了相同的问题

**Comment by lucers** [comment]
过去太久了，不太记得了，尝试检查下清单文件的相关权限配置

**Comment by liaoyong120108** [comment]
好的，感谢
---- 回复的原邮件 ----
***@***.***>发送日期2024年7月10日 ***@***.***>***@***.***>,
***@***.***>主题Re: [guolindev/PermissionX] 我想请求联系人的读写权限，回调直接返回的拒绝 (#54)
过去太久了，不太记得了，尝试检查下清单文件的相关权限配置
