### ISSUE TITLE
READ_PHONE_STATE

### ISSUE THREAD

**Issue by CCCCCCCCOOL** [guolindev/PermissionX#55]
郭哥，READ_PHONE_STATE的问题还没解决呀

**Comment by guolindev** [comment]
READ_PHONE_STATE有什么问题？

**Comment by CCCCCCCCOOL** [comment]
获取是否有READ_PHONE_STATE，一直是未拥有该权限

**Comment by guolindev** [comment]
你是用什么代码获取的是否有READ_PHONE_STATE权限？

**Comment by CCCCCCCCOOL** [comment]
我弄错了，应该是修复了，上次使用permissonX，就遇到这个问题，换了其他的框架，刚重新试了下没问题了。非常感谢。
