### ISSUE TITLE
希望能加入通知和悬浮窗权限

### ISSUE THREAD

**Issue by ZQ173** [guolindev/PermissionX#6]
如题，郭神，能加入的话最好了

**Comment by guolindev** [comment]
这个确实在我的版本计划当中，不过不是最近，排的稍微比较靠后，所以需要再多等一等。

**Comment by jaysonjh** [comment]
> 这个确实在我的版本计划当中，不过不是最近，排的稍微比较靠后，所以需要再多等一等。

通知的权限有计划什么时候可以上呢？

**Comment by guolindev** [comment]
悬浮窗权限下个版本就会加入，通知这个还需要再评估一下，因为这并不属于权限相关的功能，所以是否要加入PermissionX当中我还没有确定。

**Comment by KXwonderful** [comment]
+1

**Comment by guolindev** [comment]
1.5.0版本已支持悬浮窗权限，详情请参考 https://guolin.blog.csdn.net/article/details/119055926
