### ISSUE TITLE
为什么权限弹框会触发生命周期方法，而且触发的好乱

### ISSUE THREAD

**Issue by MLLWF** [guolindev/PermissionX#60]

**Comment by MLLWF** [comment]
这样对于实时监控视频播放界面来说很不方便，一般Dialog和PopupWindow都不会触发Activity的生命周期方法。

**Comment by guolindev** [comment]
具体触发什么生命周期方法了，有没有代码和日志能让我看一下？

**Comment by guolindev** [comment]
没有更多信息的回复，暂时先将这个问题关闭了。
