### ISSUE TITLE
拒绝且不在提醒后问题

### ISSUE THREAD

**Issue by MLLWF** [guolindev/PermissionX#62]
在拒绝且不在提醒后，主动到设置界面授权后，依然弹出授权框，再通过授权框进入设置界面授权后，其实并没有真实获取权限。

**Comment by guolindev** [comment]
那估计是你在设置界面授权错权限项了。

PermissionX有提供一个PermissionX.isGranted()函数用来确认一个权限到底是否已授权，你调用这个函数测一下你申请的那个权限就知道有没有真实授权了。
