### ISSUE TITLE
request(RequestCallback callback) callback 不走

### ISSUE THREAD

**Issue by sweetzhangxue** [guolindev/PermissionX#63]
PermissionX.init(fragmentActivity)
                .permissions(permissionList)
                .request((allGranted, grantedList, deniedList) -> {
                    Log.i(TAG, "camera callback listener=" + listener);
                    if (listener != null) {
                        listener.onResult(allGranted, grantedList, deniedList);
                    }
                });
权限授予之后，不会回调requestCallback回调

**Comment by guolindev** [comment]
从未遇到过这个情况，也没有人反馈过同类问题，建议你可以把源码下载下来，运行一下代码来测试一下基本功能。

**Comment by sweetzhangxue** [comment]
Activity继承ReactActivity时 回调都不走呢！

**Comment by CristianoLi** [comment]
我遇到了这个情况，但是我项目的原因。因为当前页面重写了onRequestPermissionsResult这个，导致在使用PermissionX的时候，其实回调是执行到了onRequestPermissionsResult里面

**Comment by s3hengwu** [comment]
是不是鸿蒙系统，偶尔出现

**Comment by s3hengwu** [comment]
是不是鸿蒙系统，偶尔出现
