### ISSUE TITLE
编译不过

### ISSUE THREAD

**Issue by 9527se** [guolindev/PermissionX#65]
环境:
andrfoid stuido 3.0.1
classpath 'com.android.tools.build:gradle:3.0.1'

android {
    compileSdkVersion 28
    buildToolsVersion '28.0.2'

    defaultConfig {
        applicationId "com.httvc.gpslocationdemo"
        minSdkVersion 16
              targetSdkVersion 28
        versionCode 1
        versionName "1.0"
    }
    compileOptions {
        sourceCompatibility 1.8
        targetCompatibility 1.8
    }

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    implementation "com.android.support:appcompat-v7:28.0.0"
    implementation 'com.google.code.gson:gson:2.8.5'
    implementation 'com.permissionx.guolindev:permission-support:1.4.0'
}

错误信息:
:app:extractTryWithResourcesSupportJarDebug UP-TO-DATE
:app:transformClassesWithStackFramesFixerForDebug
:app:transformClassesWithDesugarForDebug
Exception in thread "main" java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at com.google.devtools.build.android.desugar.CoreLibraryRewriter.reader(CoreLibraryRewriter.java:44)
	at com.google.devtools.build.android.desugar.Desugar.desugarClassesInInput(Desugar.java:388)
	at com.google.devtools.build.android.desugar.Desugar.desugarOneInput(Desugar.java:326)
	at com.google.devtools.build.android.desugar.Desugar.desugar(Desugar.java:280)
	at com.google.devtools.build.android.desugar.Desugar.main(Desugar.java:584)

 FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:transformClassesWithDesugarForDebug'.
> com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.ide.common.process.ProcessException: Error while executing java process with main class com.google.devtools.build.android.desugar.Desugar with arguments {--input E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\15.jar --output E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\desugar\debug\10.jar --input E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\55.jar --output E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\desugar\debug\40.jar --input E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\56.jar --output E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\desugar\debug\41.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\classes\debug --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\2.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\3.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\4.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\5.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\10.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\11.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\12.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\13.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\14.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\15.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\16.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\17.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\18.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\19.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\20.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\21.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\22.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\23.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\24.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\25.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\26.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\27.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\28.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\29.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\30.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\31.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\32.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\33.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\34.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\35.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\36.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\37.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\53.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\54.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\55.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\56.jar --classpath_entry E:\android_workspace\GpsLocationDemo-master\app\build\intermediates\transforms\stackFramesFixer\debug\57.jar --bootclasspath_entry C:\Users\Administrator\AppData\Local\Android\Sdk\platforms\android-28\android.jar --bootclasspath_entry C:\Users\Administrator\AppData\Local\Android\Sdk\platforms\android-28\optional\org.apache.http.legacy.jar --bootclasspath_entry C:\Users\Administrator\AppData\Local\Android\Sdk\platforms\android-28\optional\android.test.mock.jar --bootclasspath_entry C:\Users\Administrator\AppData\Local\Android\Sdk\platforms\android-28\optional\android.test.base.jar --bootclasspath_entry C:\Users\Administrator\AppData\Local\Android\Sdk\platforms\android-28\optional\android.test.runner.jar --bootclasspath_entry C:\Program Files\Android\Android Studio\jre\jre\lib\resources.jar --bootclasspath_entry C:\Program Files\Android\Android Studio\jre\jre\lib\rt.jar --bootclasspath_entry C:\Program Files\Android\Android Studio\jre\jre\lib\jsse.jar --bootclasspath_entry C:\Program Files\Android\Android Studio\jre\jre\lib\jce.jar --bootclasspath_entry C:\Program Files\Android\Android Studio\jre\jre\lib\charsets.jar --min_sdk_version 16 --desugar_try_with_resources_if_needed --desugar_try_with_resources_omit_runtime_classes}

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 13s

20 actionable tasks: 8 executed, 12 up-to-date

**Comment by guolindev** [comment]
从堆栈上看，是你的asm做了什么处理导致出现了编译不过的情况，建议你可以去掉asm再试试，是不是存在和PermissionX冲突的情况，或者是你的asm逻辑哪里有问题。

**Comment by 9527se** [comment]
我没有用过asm， 这个报错信息对于我来说太难了，我目前就是退到 1.3.0&nbsp;能用，1.4.0&nbsp;编译怎么都无法通过。你能不能写下，环境要求&nbsp;比如&nbsp;android stuido 3.0.1 gradle 4.6&nbsp; target version 27&nbsp; compile&nbsp;version 28,&nbsp; 等等，&nbsp;这样。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "guolindev/PermissionX"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月29日(星期五) 晚上9:37
收件人:&nbsp;"guolindev/PermissionX"<PermissionX@noreply.github.com&gt;;
抄送:&nbsp;"阳"<45612592@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [guolindev/PermissionX] 编译不过 (#65)





 
从堆栈上看，是你的asm做了什么处理导致出现了编译不过的情况，建议你可以去掉asm再试试，是不是存在和PermissionX冲突的情况，或者是你的asm逻辑哪里有问题。
