### ISSUE TITLE
android 10  短信权限

### ISSUE THREAD

**Issue by wenbo-ya** [guolindev/PermissionX#66]
加上短信权限，但是android 10 手机上却没有显示这一项

**Comment by guolindev** [comment]
短信权限在某些手机上可能行为会不一致，比如小米手机就永远不允许你提前申请短信权限，必须你调用短信api的时候才会弹出小米的短信授权框。建议测这种功能的时候在Android原生系统或模拟器上测试，不要以国产手机的测试结果为准。
