### ISSUE TITLE
有没有不通过onForwardToSettings方法直接跳去权限设置的方法

### ISSUE THREAD

**Issue by memorise** [guolindev/PermissionX#69]
有没有不通过onForwardToSettings方法直接跳去权限设置的方法，类似图下这种需求
![QQ截图20210203112707](https://user-images.githubusercontent.com/8307890/106694854-61bbaa80-6614-11eb-88c0-65b36d547302.png)

**Comment by guolindev** [comment]
这个你可以自己手写，其实就是一个Intent跳转就可以了，参考一下这里的写法 https://github.com/guolindev/PermissionX/blob/32be0bfba7b4b5023db1ecec001288b7b007e234/permissionx/src/main/java/com/permissionx/guolindev/request/PermissionBuilder.java#L458
