### ISSUE TITLE
郭神，RN项目里在MainActivity里调用，拒绝后没有在弹出

### ISSUE THREAD

**Issue by litaogithub** [guolindev/PermissionX#7]
如图：
![企业咚咚20200616175612](https://user-images.githubusercontent.com/10986537/84760491-b3b6ae00-affa-11ea-8eb5-c18ee90f60b5.jpg)
麻烦郭神给看看

**Comment by litaogithub** [comment]
型号：HUAWEI HRY-AL00a(青春版 10)
Android版本：10
COMPILE_SDK_VERSION = 30
TARGET_SDK_VERSION = 30
BUILD_TOOLS_VERSION = 28.0.3

**Comment by guolindev** [comment]
我没做过RN啊，如果是普通的Android项目，在华为这台手机上跑可以正常运行吗？

**Comment by litaogithub** [comment]
找到问题原因了，郭神
因为RN项目是单Activity应用，Fragment申请的权限不会回调onRequestPermissionsResult方法，回调到主MainActivity里的onRequestPermissionsResult方法了，只能在这里调你的InvisibleFragment.onRequestPermissionsResult方法
如果有别的朋友也遇到这个问题，可以参考下，哈哈
贴下MainActivity里的代码：
@Override
    public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
        super.onRequestPermissionsResult(InvisibleFragment.REQUEST_NORMAL_PERMISSIONS, permissions, grantResults);
        FragmentManager fragmentManager = getSupportFragmentManager();
        InvisibleFragment existedFragment = (InvisibleFragment) fragmentManager.findFragmentByTag("InvisibleFragment");
        if (existedFragment != null) {
            existedFragment.onRequestPermissionsResult(InvisibleFragment.REQUEST_NORMAL_PERMISSIONS,permissions,grantResults);
        }
    }

**Comment by guolindev** [comment]
怎么会有这种情况，在Fragment中申请的权限，按理说也应该会回调到Fragment中才对，这是RN的特殊流程吗？因为没接触过RN，所以不太能理解。

**Comment by fansmc** [comment]
![image](https://user-images.githubusercontent.com/4084241/85194411-20ce8a00-b300-11ea-8fd5-d3a906b62020.png)
ReactActivity里 处理了这个 回调

**Comment by guolindev** [comment]
明白了，在ReactActivity的onRequestPermissionsResult方法里没有调用super.onRequestPermissionsResult，这样父类的Activity收不到这个回调消息，也就不会分发给实际请求权限的Fragment了，这也算是一个RN的坑吧。另外就是得提醒一下其他朋友，如果你在你的Activity中重写了onRequestPermissionsResult方法，记得一定要调用super，否则Fragment会收不到分发消息。
