### ISSUE TITLE
跳转到设置页面，如果没有去开启权限，点返回回到应用页面，会一直弹窗，感觉不是很好

### ISSUE THREAD

**Issue by s3hengwu** [guolindev/PermissionX#70]
.onForwardToSettings(new ForwardToSettingsCallback() {
                            @Override
                            public void onForwardToSettings(ForwardScope scope, List<String> deniedList) {
                                scope.showForwardToSettingsDialog(deniedList, "Please allow following permissions in settings", "Allow");
                            }
                        })

**Comment by guolindev** [comment]
你改成这样就可以选择关闭弹窗了：
`
.onForwardToSettings(new ForwardToSettingsCallback() {
@override
public void onForwardToSettings(ForwardScope scope, List deniedList) {
scope.showForwardToSettingsDialog(deniedList, "Please allow following permissions in settings", "Allow", "Cancel");
}
})
`
