### ISSUE TITLE
1.5.0 特殊权限的版本啥时候能上啊「抱拳」

### ISSUE THREAD

**Issue by silentcmz** [guolindev/PermissionX#73]

**Comment by guolindev** [comment]
应该快了，主要是特殊权限得一个个单独处理，目前我已经完成了悬浮窗和WRITE_SETTINGS这几个，还差两个待完成，等全部完全之后就会发布1.5.0版本。

另外你是希望使用哪个特殊权限？我看看我正在写的这几个权限中有没有漏掉你的。

**Comment by silentcmz** [comment]
谢谢，我目前需要的是悬浮窗的权限，但是我下载代码，直接运行，发现悬浮窗代码是直接 打开所有应用列表，不能直接打开到单独应用么

**Comment by silentcmz** [comment]
> 应该快了，主要是特殊权限得一个个单独处理，目前我已经完成了悬浮窗和WRITE_SETTINGS这几个，还差两个待完成，等全部完全之后就会发布1.5.0版本。
> 
> 另外你是希望使用哪个特殊权限？我看看我正在写的这几个权限中有没有漏掉你的。

谢谢，我目前需要的是悬浮窗的权限，但是我下载代码，直接运行，发现悬浮窗代码是直接 打开所有应用列表，不能直接打开到单独应用么

**Comment by guolindev** [comment]
这个肯定是不能的。

**Comment by guolindev** [comment]
1.5.0版本已发布，谢谢支持。
