### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by 330676687** [guolindev/PermissionX#75]
> Back traces starts.
> java.lang.RuntimeException: Failure delivering result ResultInfo{who=@android:requestPermissions:, request=65537, result=0, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {com.z.tzrl/com.z.tzrl.SplashActivity}: java.lang.NullPointerException: Attempt to read from null array
> 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4464)
> 	at android.app.ActivityThread.handleSendResult(ActivityThread.java:4506)
> 	at android.app.servertransaction.ActivityResultItem.execute(ActivityResultItem.java:49)
> 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
> 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
> 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1821)
> 	at android.os.Handler.dispatchMessage(Handler.java:106)
> 	at android.os.Looper.loop(Looper.java:193)
> 	at android.app.ActivityThread.main(ActivityThread.java:6869)
> 	at java.lang.reflect.Method.invoke(Method.java)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:861)
> Caused by: java.lang.NullPointerException: Attempt to read from null array
> 	at com.permissionx.guolindev.request.InvisibleFragment.onRequestNormalPermissionsResult(InvisibleFragment.java:140)
> 	at com.permissionx.guolindev.request.InvisibleFragment.onRequestPermissionsResult(InvisibleFragment.java:97)
> 	at androidx.fragment.app.FragmentActivity.onRequestPermissionsResult(FragmentActivity.java:768)
> 	at android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7628)
> 	at android.app.Activity.dispatchActivityResult(Activity.java:7478)
> 	at android.app.ActivityThread.deliverResults(ActivityThread.java:4457)
> 	... 11 more
> Back traces ends.

**Comment by guolindev** [comment]
可以告知一下你用的哪个版本的PermissionX吗

**Comment by 330676687** [comment]
1.4.0 发的时候忘记说版本号了😂

**Comment by guolindev** [comment]
这是一个非常奇怪的情况，报空指针异常的那个参数被打上了@NonNull的标签，理论上它永远不应该是null的。所以我觉得这是一个偶现bug，你应该也是从后台抓的吧，估计没法稳定重现？

不过不管怎么样，我还是加上了一个非空判断，即使处于空的时候已经不在正常的状态了，但是至少不应该让程序崩溃。下个版本里这个bug估计就不会再出现了，感谢。
