### ISSUE TITLE
真心求解，很多应用中首次打开，一个系统权限弹窗中可以有多个权限的申请是如何实现的？

### ISSUE THREAD

**Issue by chenhucxc** [guolindev/PermissionX#77]
附上微博示例的图片链接：https://upload-images.jianshu.io/upload_images/8496923-4a23144e5f0f8c3c.png
发现QQ、微信、微博在首次安装应用打开后，都出现了这样的权限申请的情况，不知道是如何实现的，真心求解

**Comment by chenhucxc** [comment]
首先感谢你的回答
同一个手机（华为），我自己写的就没有这样的效果，代码如下
val perms = arrayOf(
            Manifest.permission.ACCESS_COARSE_LOCATION,
            Manifest.permission.ACCESS_FINE_LOCATION,
            Manifest.permission.RECORD_AUDIO,
            Manifest.permission.CAMERA,
            Manifest.permission.CALL_PHONE
 )
ActivityCompat.requestPermissions(this, perms, 10000)
试了几种方式，都是一次同意一个用户权限

**Comment by guolindev** [comment]
不太清楚，感觉又像是一个国产手机定制功能，我刚刚试了在三星手机上，微博也是一个一个权限申请的，所以这并不是标准的Android系统功能。

如果你不嫌麻烦，可以去尝试反编译一下这些APK，看看能不能找到它们申请权限地方的代码，看看有没有用什么私有的API，从而能够实现这种效果。

当然还有一种可能，是国产手机系统对这些知名的APP进行了定制优化，帮助他们一次性把所有权限都给申请了，减少用户操作次数。我不能说这种可能性有多大，但国产系统真有可能干出这种事来。验证方法是，你把你自己的测试app改成微信或微博的包名，然后用同样的代码去申请权限，看看申请界面是否变化。

可以肯定的是，这不是Android标准的权限申请接口，所以我对此也并没有什么更多的研究。

**Comment by zippo88888888** [comment]
上传至华为应用市场审核通过后就会这样，没有上传是不会的

**Comment by zippo88888888** [comment]
目前来看：华为应用市场审核通过后权限申请就会这样，没有上传或没通过是不会的

**Comment by chenhucxc** [comment]
多谢各位大佬的解答
