### ISSUE TITLE
美图手机检测权限时不会弹窗？

### ISSUE THREAD

**Issue by shiner0** [guolindev/PermissionX#81]
美图手机 android版本8.1.0 meios版本呢4.5.1

**Comment by guolindev** [comment]
能把具体的请求权限的代码贴出来一下吗？

**Comment by shiner0** [comment]
这两种方式都不行
| |
shiner
|
|
***@***.***
|
签名由网易邮箱大师定制
在2021年4月27日 21:06，Lin ***@***.***> 写道：

能把具体的请求权限的代码贴出来一下吗？
