### ISSUE TITLE
OPPO上升级安装apk提示安装包已损坏

### ISSUE THREAD

**Issue by Mr-Reid** [guolindev/PermissionX#83]
PermissionX.init(this)
                .permissions(Manifest.permission.READ_EXTERNAL_STORAGE, Manifest.permission.WRITE_EXTERNAL_STORAGE)
                .onExplainRequestReason((scope, deniedList, beforeRequest) -> scope.showRequestReasonDialog(deniedList, "即将申请的权限是程序必须依赖的权限", "我已明白"))
                .onForwardToSettings((scope, deniedList) -> scope.showForwardToSettingsDialog(deniedList, "您需要去应用程序设置当中手动开启权限", "我已明白"))
                .request((allGranted, grantedList, deniedList) -> {
                    if (allGranted) {
                        try {
                            installApkO();
                        } catch (Exception e) {
                            e.printStackTrace();
                        }
                    } else {
                        //TODO
                    }
                });

private void installApkO() {
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.O) {
            //是否有安装位置来源的权限
            boolean haveInstallPermission = getPackageManager().canRequestPackageInstalls();
            if (haveInstallPermission) {
                //"8.0手机已经拥有安装未知来源应用的权限，直接安装！
                ApkInstallTool.installApk(this);
            } else {

                PadDialogTips dialog = new PadDialogTips("Permission_Open_Setting",  false);
                dialog.setClickListener(() -> {
                    Uri packageUri = Uri.parse("package:" + BuildConfig.APPLICATION_ID);
                    Intent intent = new Intent(Settings.ACTION_MANAGE_UNKNOWN_APP_SOURCES, packageUri);
                    startActivityForResult(intent, 123);
                });
                dialog.show(getSupportFragmentManager(), "PadDialogTips");
            }
        } else {
            ApkInstallTool.installApk(this);
        }
    }

public static void installApk(Context context) {
        Intent intent = new Intent(Intent.ACTION_VIEW);
        File file = new File(Environment.getExternalStorageDirectory(), "qq.apk");
        if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            Uri apkUri = FileProvider.getUriForFile(context, BuildConfig.APPLICATION_ID + ".fileprovider", file);
            context.grantUriPermission(context.getPackageName(), apkUri, Intent.FLAG_GRANT_WRITE_URI_PERMISSION | Intent.FLAG_GRANT_READ_URI_PERMISSION);
            intent.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK | Intent.FLAG_GRANT_WRITE_URI_PERMISSION | Intent.FLAG_GRANT_READ_URI_PERMISSION );
            intent.setDataAndType(apkUri, "application/vnd.android.package-archive");
        } else {
            intent.setFlags(Intent.FLAG_ACTIVITY_NEW_TASK);
            Uri uri = Uri.fromFile(file);
            intent.setDataAndType(uri, "application/vnd.android.package-archive");
        }
        context.startActivity(intent);

    }

在Oppo上自动升级安装时提示安装包已损坏, 小米和华为测试没问题
测试去掉PermissionX  换成其他权限申请框架就没问题了    能看下是什么原因吗

**Comment by guolindev** [comment]
这个我也看不出来，PermissionX和APK包貌似并没有什么交集，PermissionX只负责申请权限，也不会对APK进行任何操作，所以OPPO提示安装包失败很难让我和PermissionX产生什么关联。

你的上述用例当中就是去申请了READ_EXTERNAL_STORAGE和WRITE_EXTERNAL_STORAGE权限，如果申请成功了，那么PermissionX的工作也就结束了，后面都是你自己的逻辑了。

**Comment by guolindev** [comment]
没有收到更多回复，暂时先将问题关闭。
