### ISSUE TITLE
Android11 取消Manifest.permission.WRITE_EXTERNAL_STORAGE

### ISSUE THREAD

**Issue by cuibg** [guolindev/PermissionX#84]
Android11 取消了这个权限，如果继续请求的话，返回的是失败，我看您再代码中没有做 特殊处理！

**Comment by guolindev** [comment]
不需要做什么特殊处理呀，你用原生的API去请求WRITE_EXTERNAL_STORAGE会得到什么结果呢？

**Comment by cuibg** [comment]
@guolindev 假如说把WRITE_EXTERNAL_STORAGE权限的maxsdk 置为28，那么在Android11请求的时候，会返回请求权限失败！

**Comment by guolindev** [comment]
那你用Android原生的API去请求WRITE_EXTERNAL_STORAGE能成功吗？

**Comment by cuibg** [comment]
AndroidManifest中设置WRITE_EXTERNAL_STORAGE的权限maxsdk为28的话，在Android11上是失败的

**Comment by guolindev** [comment]
是的呀，你用原生的也是失败，PermissionX又怎能让你成功呢？PermissionX只是在原生API基础上做封装，让用法变得更简单，但不能做到原生失败的权限用PermissionX请求就能成功。

**Comment by cuibg** [comment]
@guolindev 嗯嗯，好的 ，建议在使用上加入target sdk，这样不属于这个范畴就返回true
