### ISSUE TITLE
发现了个Bug，我在act的基类中的OnResume方法写了请求权限，并且拒绝了

### ISSUE THREAD

**Issue by ChawLoo** [guolindev/PermissionX#87]
死循环。。。。。。
我在BaseActivity中的onResume请求写入存储权限，并且拒绝且不提醒，直接死循环走onResume和onPause  最终卡Cpu卡内存，手机差点直接ANR。

**Comment by ChawLoo** [comment]
本来想公众号，直接给你说，想想还是提个issues好了

**Comment by guolindev** [comment]
这个问题是由于你在onResume里请求权限，权限被拒绝后会弹出dialog来提醒你，弹出dialog会触发onResume再次执行，然后你又在onResume里请求权限，这样就死循环了。

所以解决办法就是不要在onResume里请求权限。
