### ISSUE TITLE
InvisibleFragment 能否在权限处理流程完毕之后，remove 出 FragmentManager

### ISSUE THREAD

**Issue by itsMelo** [guolindev/PermissionX#88]
当前问题：InvisibleFragment 每次被 add 进来以后，就一直存在内存中了
期望解决：当权限整个流程处理完毕以后，将 InvisibleFragment 实例 remove 出 fragmentManager
现状就是 InvisibleFragment 实例个数是和当前 Activity/Fragment 个数对应的，并且没有 remove 出栈的操作。

**Comment by guolindev** [comment]
这个我得再参考一下，因为如果只是出于内存方面的考虑，InvisibleFragment是非常轻量级的，完全不会对app的性能造成任何影响。反倒是移除再加入，频繁这种操作对性能的影响更大。但如果有些app的功能逻辑依赖于在Activity中获取嵌入的Fragment数量，这样InvisibleFragment的存在就会导致这样的逻辑很难写，我还没考虑清楚。话说很多开源库使用的都是这种添加不可见Fragment的方式，像Glide这种会在运行结束后把隐藏Fragment回收掉吗？

**Comment by itsMelo** [comment]
内存方面可能确实影响不大，但是就像你说的，InvisibleFragment 如果常驻栈中，并且这个栈可能是 Activity（fragmentManager）或者是 Fragment（childFragmentManager），可能会对原有的 app Activity/Fragment 的栈管理造成入侵式的伤害，使用者可能不了解这里的原理，而导致比较严重的线上问题，从权限的作用域去考虑，自然是希望申请时发生变化，申请完毕后一切都可以复原，达到理论上完全无损。Glide 我也没研究过哈，也感谢郭神提供的开源方案，我本地是把 InvisibleFragment 移除栈了，其实并不算是多么频繁的操作。

**Comment by guolindev** [comment]
好的，那我再评估一下方案，我觉得整体影响应该不大，如果移除并不会对功能性造成什么影响，那我也考虑在下个版本中移除，谢谢建议。

**Comment by BugRui** [comment]
@guolindev 或者考虑一下使用DialogFragment代替？

**Comment by guolindev** [comment]
@itsMelo   你建议的这个功能已在这条commit中加入 https://github.com/guolindev/PermissionX/commit/180923640500ccdd2d241410ea91b04b58363c79

会随着下次PermissionX发版本正式引入，感谢支持。
