### ISSUE TITLE
8.1 以下版本

### ISSUE THREAD

**Issue by mengsr** [guolindev/PermissionX#89]
android.content.pm.PackageManager$NameNotFoundException
android.permission.FOREGROUND_SERVICE
onForwardToSettings

                            scope.showForwardToSettingsDialog(deniedList, "请在设置中允许以下权限", "允许");
会报错

**Comment by guolindev** [comment]
FOREGROUND_SERVICE是什么，没这种运行时权限吧

**Comment by mengsr** [comment]
是勒  复制的时候过加了。。
