### ISSUE TITLE
PermissionX获取后台定位权限在8.0的手机上，后台定位权限会进入deniedList

### ISSUE THREAD

**Issue by lucers** [guolindev/PermissionX#9]
如题

**Comment by guolindev** [comment]
因为后台定位权限是Android 10系统才引入的，8.0上并没有这个权限，所以会进入deniedList。我其实也考虑过这个权限在低于Android 10系统的情况下到底是进入grantedList还是deniedList，但是由于使用系统的API判断后台权限会自动进入deniedList，如果我把它放到gratedList当中会和系统的行为不一致，可能又会引起其他问题。

**Comment by lucers** [comment]
我看安卓文档上说，10.0以下，如果用户授予了运行时定位权限，那么后台运行权限就是true的，所以这里低版本下应该判断定位权限是否授予决定进入grantedList还是deniedList？

**Comment by guolindev** [comment]
因为10.0以下，还没有ACCESS_BACKGROUND_LOCATION这个权限，后台定位权限确实是true，但是ACCESS_BACKGROUND_LOCATION这个权限是false。也就是说，你如果在问10.0以下，应用程序是否可以后台定位，这个确实可以。但如果你在问，10.0以下，ACCESS_BACKGROUND_LOCATION是授权还是没授权，答应是没授权。所以PermissionX在按照系统的返回值来返回给开发者。你可以自己在10.0以下的版本中用系统的API尝试一下，判断ACCESS_BACKGROUND_LOCATION这个权限，结果一定是未授权。
