### ISSUE TITLE
android.permission.ACCESS_BACKGROUND_LOCATION 在华为手机8.1.0上崩溃

### ISSUE THREAD

**Issue by tianjinrui** [guolindev/PermissionX#96]
系统版本：Android 8.1.0,level 27
ROM ：HuaWei/EMOTION
crash 标题 ： 
android.content.pm.PackageManager$NameNotFoundException
android.permission.ACCESS_BACKGROUND_LOCATION
com.permissionx.guolindev.dialog.a.d(SourceFile:4)

详细日志：
java.lang.RuntimeException:Failure delivering result ResultInfo{who=@android:requestPermissions:, request=1194976313, result=-1, data=Intent { act=android.content.pm.action.REQUEST_PERMISSIONS (has extras) }} to activity {xxx.xxxx.android/com.xxxxxx.main.MainActivity}: android.content.pm.PackageManager$NameNotFoundException: android.permission.ACCESS_BACKGROUND_LOCATION
2
android.app.ActivityThread.deliverResults(ActivityThread.java:5042)
3
......
4
Caused by:
5
android.content.pm.PackageManager$NameNotFoundException:android.permission.ACCESS_BACKGROUND_LOCATION
6
android.app.ApplicationPackageManager.getPermissionInfo(ApplicationPackageManager.java:330)
7
com.permissionx.guolindev.dialog.a.d(SourceFile:4)
8
com.permissionx.guolindev.dialog.a.onCreate(SourceFile:4)
9
android.app.Dialog.dispatchOnCreate(Dialog.java:516)
10
android.app.Dialog.show(Dialog.java:382)
11
com.permissionx.guolindev.request.e.i(SourceFile:6)
12
com.permissionx.guolindev.request.e.j(SourceFile:2)
13
com.permissionx.guolindev.request.d.a(SourceFile:1)
14
base.sys.utils.w.j(SourceFile:7)
15
base.sys.utils.w.g(Unknown Source:0)
16
base.sys.utils.a.a(Unknown Source:0)
17
com.permissionx.guolindev.request.InvisibleFragment.r(SourceFile:17)
18
com.permissionx.guolindev.request.InvisibleFragment.onRequestPermissionsResult(SourceFile:2)
19
androidx.fragment.app.FragmentManager$11.onActivityResult(SourceFile:14)
20
androidx.fragment.app.FragmentManager$11.onActivityResult(SourceFile:1)
21
androidx.activity.result.ActivityResultRegistry.doDispatch(SourceFile:3)
22
androidx.activity.result.ActivityResultRegistry.dispatchResult(SourceFile:3)
23
androidx.activity.ComponentActivity.onRequestPermissionsResult(SourceFile:4)
24
androidx.fragment.app.FragmentActivity.onRequestPermissionsResult(SourceFile:2)
25
android.app.Activity.dispatchRequestPermissionsResult(Activity.java:7786)
26
android.app.Activity.dispatchActivityResult(Activity.java:7637)
27
android.app.ActivityThread.deliverResults(ActivityThread.java:5038)
28
android.app.ActivityThread.handleSendResult(ActivityThread.java:5086)
29
android.app.ActivityThread.-wrap20(Unknown Source:0)
30
android.app.ActivityThread$H.handleMessage(ActivityThread.java:2071)
31
android.os.Handler.dispatchMessage(Handler.java:109)
32
android.os.Looper.loop(Looper.java:166)
33
android.app.ActivityThread.main(ActivityThread.java:7555)
34
java.lang.reflect.Method.invoke(Native Method)

翻阅了代码发现：
 // If app runs under Android Q, there's no ACCESS_BACKGROUND_LOCATION permissions.
 // We remove it from request list, but will append it to the request callback as denied permission.

**Comment by guolindev** [comment]
8.0系统还没有这个权限，你在编写代码的时候IDE就会提醒你这个错误了，这个和PermissionX无关。

**Comment by tianjinrui** [comment]
问题是我的项目里没有用到这个权限，但是却报了这个错误。



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Lin Guo ***@***.***&gt;
发送时间: 2021年7月3日 13:28
收件人: guolindev/PermissionX ***@***.***&gt;
抄送: tianjinrui ***@***.***&gt;, Author ***@***.***&gt;
主题: 回复：[guolindev/PermissionX] android.permission.ACCESS_BACKGROUND_LOCATION 在华为手机8.1.0上崩溃 (#96)





 
8.0系统还没有这个权限，你在编写代码的时候IDE就会提醒你这个错误了，这个和PermissionX无关。

**Comment by tianjinrui** [comment]
我再次描述一下问题哈：
我的项目里面没有申请这个权限，然后我发现bugly上有报这个崩溃，而且崩溃的手机也只有华为，次数目前是一次，我在看了你的源码后，我发现尽管我没有申请这个权限，但是你也会把这个权限
加入到拒绝队列里面（这可能会导致崩溃）


ps：我知道Android Q 以下没有这个权限，我不是因为申请这个权限导致的崩溃
希望郭大神重新看一下这个问题哇


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "guolindev/PermissionX"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年7月3日(星期六) 中午1:28
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [guolindev/PermissionX] android.permission.ACCESS_BACKGROUND_LOCATION 在华为手机8.1.0上崩溃 (#96)





 
8.0系统还没有这个权限，你在编写代码的时候IDE就会提醒你这个错误了，这个和PermissionX无关。

**Comment by guolindev** [comment]
哦？那就奇怪了。

你是在哪里看到尽管没有申请这个权限，我也会把这个权限加入到拒绝队列里面的，能把源码的位置指出来吗？

**Comment by tianjinrui** [comment]
// If app runs under Android Q, there's no ACCESS_BACKGROUND_LOCATION permissions.
// We remove it from request list, but will append it to the request callback as denied permission.
我看到了 上面的注释
这是说  如果申请了，会在 Android Q以下移除（这里我说错了 ）

那现在的问题有点奇怪了，因为我确实没有申请这个权限，并且看bugly的日志
android.app.ActivityThread.deliverResults  说是在回调的时候发生crash

**Comment by guolindev** [comment]
我知道这个崩溃是什么原因了，确实一个PermissionX中的漏洞。

但是你一定是在哪里申请了ACCESS_BACKGROUND_LOCATION权限，不然这个漏洞还是不会触发的。或者不是你主动申请的，但是可能是你间接调用了什么导致多申请了这个权限？

我会在下个版本中修复这个漏洞，但是只能保证程序不会崩溃，你的程序还是会收到一个拒绝的ACCESS_BACKGROUND_LOCATION回调，所以如果你有兴趣可以查查到底是在哪里申请的这个权限。

**Comment by tianjinrui** [comment]
感谢，我之后会进一步确认 到底是哪里申请了这个权限

**Comment by guolindev** [comment]
1.5.0版本中已修复此问题。
