### ISSUE TITLE
链表数据结构，新增3个任务以上，中间任务是否就丢失了

### ISSUE THREAD

**Issue by Swer316828** [guolindev/PermissionX#99]
1.RequestChain 类
 /**
     * Add a task into task chain.
     * @param task  task to add.
     */
    public void addTaskToChain(BaseTask task) {
        **if (headTask == null) {
            headTask = task;
        }
        // add task to the tail
        if (tailTask != null) {
            tailTask.next = task;
        }
        tailTask = task;**
    }

2.PermissionBuilder 中

   /**
     * Request permissions at once, and handle request result in the callback.
     *
     * @param callback Callback with 3 params. allGranted, grantedList, deniedList.
     */
    public void request(RequestCallback callback) {
        requestCallback = callback;
        // Build the request chain.
        // RequestNormalPermissions runs first.
        // Then RequestBackgroundLocationPermission runs.
        RequestChain requestChain = new RequestChain();
        **requestChain.addTaskToChain(new RequestNormalPermissions(this));
        requestChain.addTaskToChain(new RequestBackgroundLocationPermission(this));**
        requestChain.runTask();
    }

  addTaskToChain(); 方法调用三次即添加3次任务，中间任务是否就丢失了

**Comment by guolindev** [comment]
为什么会丢失呢？
